### ISSUE TITLE
Instance name does not show the name of vmss and shows an index

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/cluster-api-provider-azure#1068]
While working on https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1058 notice that we don't have enough information to get the name/ips of the vmss nodes to be able to ssh

When doing the investigation, notice that the `azuremachinepools` status field does not show the name of the node and it shows the index. `k get azuremachinepools.exp.infrastructure.cluster.x-k8s.io  machinepool-template-mp-0 -o yaml`

```
status:
  instances:
  - instanceName: "0"
    latestModelApplied: true
    providerID: azure:///subscriptions/XXXX/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0/virtualMachines/0
    provisioningState: Succeeded
    version: v1.19.4
  - instanceName: "3"
    latestModelApplied: true
    providerID: azure:///subscriptions/XXXX/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0/virtualMachines/3
    provisioningState: Succeeded
    version: v1.19.4
  provisioningState: Succeeded
  ready: true
  replicas: 2
  version: v1.19.4
````

So in this case will be good if we have an `index` field and the `instanceName` is actually the `computerName` of the vmms node

like when we run the `az vmss get-instance-view --resource-group machinepool-template --name machinepool-template-mp-0 --instance-id 0`

```
{
  "assignedHost": null,
  "bootDiagnostics": {
    "consoleScreenshotBlobUri": null,
    "serialConsoleLogBlobUri": null,
    "status": null
  },
  "computerName": "machinepool-template-mp-0000000",
....
```

Using the computer name to try to ssh using the control-plane machine is not possible

/cc @CecileRobertMichon
