### ISSUE TITLE
Additional Configurability with Azure Private clusters

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes-sigs/cluster-api-provider-azure#1159]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
CAPZ feels to currently be slightly opinionated with the set of resources it creates and does not offer configurability to disable the creation of some resources.  There could be instances where the creation of a resource is undesired by the end user, or even not permitted per an organization security policy. For instance:

1. A user may not want to use a private Azure DNS zone b/c their environment has others means of providing DNS (perhaps through deploying their own Activity Directory service). 
2. A user may not want to have public loadbalancers provisioned b/c the cluster will not have any externally visible services so an ingress path is not required (or ingress is provided through alternative means like Big-IP F5 devices w/ F5 ingress controller).
3. A user may not want to have public loadbalancers provisioned b/c outbound connectivity for worker and controlplane nodes is not permitted because the environment is air-gapped (container images, binaries, linux packages could be served through internal artifact repos like Artifactory or Nexus).  Some organizations also require that egress traffic travel through a proxy device to reach the internet so that additional network edge policies can be enforced. 
4. A user may not want to create public ip addresses b/c the organization enforces a policy in the Azure subscription that prevents the creation of public ips. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 0.4.10
- Kubernetes version: (use `kubectl version`): 1.18.12
- OS (e.g. from `/etc/os-release`): ubuntu 1804

**Comment by devigned** [comment]
I think the challenge here is how to describe and then choreograph the behaviors CAPZ depends upon. For example, IIRC Azure private DNS is used to deal with hairpin routing in the control plane. If there is a way we could express that dependency or correct that behavior is such a way that we can make it more amenable to other infra, let's do it.

We'd be excited to work through these opinionated resources to enable these scenarios.

**Comment by wwsean08** [comment]
I had to work around the DNS issue as our network is using a custom DNS server instead of the default azure provider, thus the private DNS wasn't getting injected.  My workaround was to update the `KubeadmConfigTemplate` to override the hosts file with the proper dns record, in my case I'm doing i via helm.  This way my nodes could talk to each other just fine (though temporarily I had to SSH into the first control plane node and point the capz.io address at 127.0.0.1 until more nodes came up).

Below is an example of what I did to temporarily work around this issue in a private cluster (via helm):

```
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-md-0
  annotations:
    "helm.sh/resource-policy": keep
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: worker-node-azure.json
            name: {{ .Values.clusterName }}-md-0-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      - content: |
          ::1            localhost ip6-localhost ip6-loopback
          127.0.0.1  localhost localhost.local
          {{ .Values.vnet.subnets.controlPlane.lbip }} apiserver.{{ .Values.clusterName }}.capz.io
        owner: root:root
        path: /etc/hosts
        permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-config: /etc/kubernetes/azure.json
            cloud-provider: azure
          name: '{{ `{{ ds.meta_data["local_hostname"] }}` }}'
      useExperimentalRetryJoin: true
```
