### ISSUE TITLE
Ability to define multiple subnets and assign the MachinePool on the subnet

### ISSUE THREAD

**Issue by dmeytin** [kubernetes-sigs/cluster-api-provider-azure#1362]
/kind feature

As a user I would like to have multiple MachinePools in the cluster with ability to assign each machine pool on the dedicated subnet

AzureCluster definition already supports subnet definitions, but there is no option to assign MachinePool on the defined subnet

````
  networkSpec:
    vnet:
      name: dimacapzworker-1-vnet
      cidrBlocks:
        - 10.0.0.0/16
    subnets:
      - name: my-subnet-cp
        role: control-plane
        cidrBlocks:
          - 10.0.1.0/24
      - name: my-subnet-node
        role: node
        cidrBlocks:
          - 10.0.2.0/24
```


The expected reference could be as following:

```
spec:
  subnet:
    name: my-subnet-node
```
