### ISSUE TITLE
Support for Shared Image Gallery images requiring a `Plan`.

### ISSUE THREAD

**Issue by whites11** [kubernetes-sigs/cluster-api-provider-azure#1463]
/kind feature

**Describe the solution you'd like**

I am trying to run a CAPZ cluster on [`Flatcar Container Linux`](https://kinvolk.io/flatcar-container-linux/) by Kinvolk

Preamble: when running VMs with that image on Azure (I'm talking about a plain VM now, no CAPZ involved) it is required to set the `Plan` field in the VM spec or the VM creation fails with the following error:

```
Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request.
```

So I made some changes to [`image-builder`](https://github.com/kubernetes-sigs/image-builder) in order to add a new build target `build-azure-sig-flatcar` that builds a CAPZ image starting from the following image:

(this is a section of the packer var file)
```
  "build_name": "flatcar",
  "distribution": "flatcar",
  "distribution_release": "stable",
  "distribution_version": "all",
  "image_offer": "flatcar-container-linux-free",
  "image_publisher": "kinvolk",
  "image_sku": "stable",
```

So far so good, the image gets built and I can see it in my shared image gallery:

![sigs](https://user-images.githubusercontent.com/868430/122935415-9c7a7100-d370-11eb-8714-46dd6bb933d5.png)

I then tried to run a capz cluster using my custom image for the control plane VM, using this CR:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  template:
    spec:
      image:
        sharedGallery:
          gallery: GSClusterAPI
          name: capi-flatcar-all
          resourceGroup: capi-image-builder
          subscriptionID: REDACTED
          version: 0.3.1624260268
       ...
```

The VM gets created but it goes into a failed state with the error

```
Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request.
```

I then hacked CAPZ code in order to set the `Plan` field as instructed:

```
virtualMachine := compute.VirtualMachine{
    Plan:     &compute.Plan{
        Publisher: to.StringPtr("kinvolk"),
        Name:      to.StringPtr("stable"),
        Product:   to.StringPtr("flatcar-container-linux-free"),
    },
    ...
```

And the VM gets created successfully.

Problem: it is impossible to use a `Shared Image Gallery` image AND get a `Plan` set because it is not allowed to specify both the `spec/template/spec/image/sharedGallery` and `spec/template/spec/image/marketPlace`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: latest master
