### ISSUE TITLE
VMSS rolling update proceeds before old instance is deleted

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#1484]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Create a cluster with a machine pool, set max surge to 25%:

```
spec:
    identity: None
    location: eastus2
    providerID: azure:///subscriptions/redacted/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0
    providerIDList:
    - azure:///subscriptions/redacted/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0/virtualMachines/1
    - azure:///subscriptions/redacted/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0/virtualMachines/2
    - azure:///subscriptions/redacted/resourceGroups/machinepool-template/providers/Microsoft.Compute/virtualMachineScaleSets/machinepool-template-mp-0/virtualMachines/3
    strategy:
      rollingUpdate:
        deletePolicy: Oldest
        maxSurge: 25%
        maxUnavailable: 1
      type: RollingUpdate
```

25% with 3 replicas should be == 1 

When I start a rolling update, 1 new instance gets created as expected. However, as soon as that new instance is created, another one starts provisioning even though no old instance has been deleted yet, resulting in 5 instances.

![Screen Shot 2021-07-01 at 12 12 24 PM](https://user-images.githubusercontent.com/8650424/124177837-a170ac00-da65-11eb-9808-33224dc1bbb6.png)

**What did you expect to happen:**

Only replica count + n surge instances at all time so I don't use extra quota. The 2nd new instance should wait for the first to be done deleted before it starts creating.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
