### ISSUE TITLE
Azure ManagedMachinePool provider id scheme is incompatible with capi

### ISSUE THREAD

**Issue by sadysnaat** [kubernetes-sigs/cluster-api-provider-azure#1503]
/kind bug
/area managedclusters

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Create a managed cluster with one azuremanagedmachinepool [pool1]
azuremanagedmachinepool and node refs are synced correctly 

add one more azuremanagedmachinepool [pool2]
pool2 status.nodeRef will have nodes from pool1

**What did you expect to happen:**
pool2 status.nodeRef will have nodes from pool2

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I think this happens because 
the azure managedmachinepool  node's providerid is incompatible with capi providerid 

Where capi expects last segment of providerid to be unique instance id 
https://github.com/kubernetes-sigs/cluster-api/blob/37c862b5c9256d7ae65cd8ee8ddd7a103d51fe90/controllers/noderefutil/providerid.go#L34-L40

azure providerid for managedmachinepoolnode is 
`azure:///subscriptions/<subscription>resourceGroups/<resourcegroup>/providers/Microsoft.Compute/virtualMachineScaleSets/aks-newworkw7y1-28238572-vmss/virtualMachines/0`

which capi parses as follows 
provider: azure 
id: 0

which causes noderef util in capi to match incorrect nodes in machinepoolstatus

**Environment:**

- cluster-api-provider-azure version: 0.4.15
- Kubernetes version: (use `kubectl version`): 1.21.1 
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by CecileRobertMichon** [comment]
cc @alexeldeib @devigned 

is this something we'd run into for MachinePools/MachinePoolMachines as well?

**Comment by devigned** [comment]
@CecileRobertMichon I think we did, then changed to using the consistent helper method for provider IDs.

**Comment by alexeldeib** [comment]
do you have an example of a repro of this? The code you linked is only used by machine controller, not machine pool controller (as far as I can currently find). 

machine pool controller [uses ](https://github.com/kubernetes-sigs/cluster-api/blob/37c862b5c9256d7ae65cd8ee8ddd7a103d51fe90/exp/controllers/machinepool_controller_noderef.go#L85)`spec.ProviderIDList`, which is copied from ammp `spec.ProviderIDList`, which is set based on the VMSS or Kubernetes nodes in that agentpool as expected.

it does use the provider ID functions you mentioned, but it looks like it handles all the normalization into a map using the instance ID [here](https://github.com/kubernetes-sigs/cluster-api/blob/37c862b5c9256d7ae65cd8ee8ddd7a103d51fe90/exp/controllers/machinepool_controller_noderef.go#L179-L221). With that normalization, instance IDs _**will**_ be unique, because VMSS instance IDs are unique per VMSS. 

I took a look at some of the artifacts from successful CI runs I've been working on, and they seem to work as expected: 
- [agentpool0](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1488/pull-cluster-api-provider-azure-e2e-exp/1413627990528495616/artifacts/clusters/bootstrap/resources/capz-e2e-g7tdac/MachinePool/agentpool0.yaml)
```yaml
spec:
  clusterName: capz-e2e-g7tdac
  providerIDList:
  - azure:///subscriptions/===REDACTED===/resourceGroups/mc_capz-e2e-g7tdac_capz-e2e-g7tdac_francecentral/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool0-38356254-vmss/virtualMachines/0
status:
  nodeRefs:
  - name: aks-agentpool0-38356254-vmss000000
    uid: b024fb10-3126-410b-adbc-608c3e40e131
```
- [agentpool1](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1488/pull-cluster-api-provider-azure-e2e-exp/1413627990528495616/artifacts/clusters/bootstrap/resources/capz-e2e-g7tdac/MachinePool/agentpool1.yaml)
```yaml
spec:
  clusterName: capz-e2e-g7tdac
  providerIDList:
  - azure:///subscriptions/===REDACTED===/resourceGroups/mc_capz-e2e-g7tdac_capz-e2e-g7tdac_francecentral/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool1-38356254-vmss/virtualMachines/0
status:
  nodeRefs:
  - name: aks-agentpool1-38356254-vmss000000
    uid: 13854b21-9ad7-4900-a9f3-96ec6d5ecf9c
```
