### ISSUE TITLE
Omit nat-gateway details from spec if no nat-gateway is defined

### ISSUE THREAD

**Issue by jackfrancis** [kubernetes-sigs/cluster-api-provider-azure#1581]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

This doesn't seem to affect anything, but the generated AzureCluster spec injects an "empty" nat-gateway definition in a subnet if there is no nat-gateway defined. For example:

```
    - cidrBlocks:
      - 10.0.0.0/16
      name: control-plane-subnet
      natGateway:
        ip:
          name: ""
      role: control-plane
      routeTable: {}
      securityGroup:
        name: acse-test-capz-68912-1-controlplane-nsg
```

**What did you expect to happen:**

I would expect the `natGateway` property to be entirely removed from the above subnet spec.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: v1alpha4
- Kubernetes version: (use `kubectl version`): v1.21.3
- OS (e.g. from `/etc/os-release`):
