### ISSUE TITLE
Resolving internal "apiserver.<cluster name>.capz.io" from Peering Management VNet

### ISSUE THREAD

**Issue by sshiba** [kubernetes-sigs/cluster-api-provider-azure#1601]
/kind feature

_Scenario_:
Deploying a _Private Workload_ cluster from a _Management_ cluster in a peered VNet.
See https://capz.sigs.k8s.io/topics/api-server-endpoint.html#warning

_Issue_:
When deploying a _private_ workload cluster from a _management_ vm (peered vnet) it gets stuck trying to complete the bootstrap configuration of the control plane node. The reason is that _management_ vm is not capable of resolving the name of the **internal** API server (LB) `apiserver.<cluster name>.capz.io` of the _workload_ cluster.

_Feature request_:
To simplify the setup of the _management_ environment (peered vnet) the request is to provide a mechanism allowing to configure the DNS of the peered _management_ vnet to resolve the name of the _workload_ cluster's **internal** API server LB. For example, having the _management_ DNS to resolve `apiserver.<cluster name>.capz.io` to `172.23.1.100`.

```
kind: AzureCluster
spec:
  networkSpec:
    apiServerLB:
      name: target-cluster-internal-lb
      type: Internal
      frontendIPs:
        - name: lb-private-ip-frontend
          privateIP: 172.23.1.100
```

**Environment:**
- cluster-api-provider-azure version: v0.5.1
- Kubernetes version: (use `kubectl version`): 1.21.1
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04
