### ISSUE TITLE
Azure Cluster Identity doesn't validate with ManualServicePrincipal

### ISSUE THREAD

**Issue by dmlb2000** [kubernetes-sigs/cluster-api-provider-azure#1947]
/kind bug

**What steps did you take and what happened:**
I was exercising some documentation [here](https://capz.sigs.k8s.io/topics/multitenancy.html?highlight=azureclusteridentity#manual-service-principal-identity) that discussed using an alternative to ServicePrincipal for the Azure Cluster Identity. Seems that ManualServicePrincipal is in the code but not in the validation somehow?

Resource I'm trying to define
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 52a5815d-4d06-4c21-8e6e-ae577a3add5a
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: 87942043-9e9d-43d9-b255-7bdaa67d5aab
  type: ManualServicePrincipal
```

Command and output...
```
$ kubectl apply -f azure-k8s-cluster.yml
...
The AzureClusterIdentity "cluster-identity" is invalid: spec.type: Unsupported value: "ManualServicePrincipal": supported values: "ServicePrincipal", "UserAssignedMSI"
```

**What did you expect to happen:**

I've got a secret and service principal from our Azure subscription (that's what the cloud team gave me). So, I'm using those directly into cluster-api to build out an Azure cluster. Seems like some validation isn't working somewhere.

**Environment:**

- cluster-api-provider-azure version: us.gcr.io/k8s-artifacts-prod/cluster-api-azure/cluster-api-azure-controller:v1.1.0
- Kubernetes version: (use `kubectl version`): v1.21.5
- OS (e.g. from `/etc/os-release`): CentOS, Redhat, Ubuntu, Windows 10, depends on which part you are asking about.
