### ISSUE TITLE
API Server LB Port

### ISSUE THREAD

**Issue by dmlb2000** [kubernetes-sigs/cluster-api-provider-azure#1952]
/kind feature

**Describe the solution you'd like**
Some organizations really like to block all out going ports. As a result specifying the API Server LB Port would be really helpful so users can use an institutionally approved port (like 443).

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: mycluster
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: westus
  networkSpec:
    apiServerLB:
      type: Internal
      frontendIPs:
        - name: lb-private-ip-frontend
          privateIP: 10.16.36.250
          port: 443
```

**Anything else you would like to add:**
Nope, this will probably be enough.

**Environment:**

- cluster-api-provider-azure version: 1.1.0
- Kubernetes version: (use `kubectl version`): 1.22.4
- OS (e.g. from `/etc/os-release`): Windows 10, Ubuntu, CentOS, Redhat, depends on what you are asking about.

**Comment by dmlb2000** [comment]
I tried setting the endpoint directly using the following, seems like the controller is sending the API endpoint back to the kubeadm control plane manager somehow...

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: datahub
  namespace: default
spec:
  controlPlaneEndpoint:
    port: 443
    host: 192.168.36.250
```

Seems like the rest of cluster api ignores that key...

**Comment by dmlb2000** [comment]
I think I found it, still trying to figure out the responsibilities between cluster-api and the providers...

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mycluster
  namespace: default
spec:
  clusterNetwork:
    apiServerPort: 443
```
