### ISSUE TITLE
Support AzureManagedCluster BYO vnet in different RG

### ISSUE THREAD

**Issue by ninlil** [kubernetes-sigs/cluster-api-provider-azure#1954]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
I'm creating a AKS-cluster and I've modified the AzureManagedControlPlane and specified
```yaml
  virtualNetwork:
    name: EXISTING_VNET_NAME
    cidrBlock: 10.18.22.0/24
    subnet:
      name: NAME_OF_SUBNET_IN_ABOVE_VNET
      cidrBlock: 10.18.22.0/24
```
The names and cidr-ranges match exactly what already exists.
The VNET is located in the same "location/region" but a different Resource-group.

When deployed a new VNET with the same name is created in the resource-group, although when using the Azure-portal i can actually select the existing VNET even when it's in a different resource-group.

**What did you expect to happen:**
The cluster to reuse my manually prepared VNET,

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: 1.1.0
- Kubernetes version: (use `kubectl version`):  1.21.1 (kind-cluster)
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS

**Comment by dmlb2000** [comment]
I did figure out how to do this using my config it looks like the following...

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: mycluster
  namespace: default
spec:
  networkSpec:
    vnet:
      resourceGroup: netvnet_locked
      name: mycluster_VNET
    subnets:
      - name: defaulthigh
        role: control-plane
        cidrBlocks:
          - 192.168.36.128/25
      - name: default
        role: node
        cidrBlocks:
          - 192.168.36.0/25
```

I also make sure the resource group that contains the vnet is locked so nothing can remove it without a double click through the UI.
