### ISSUE TITLE
AzureClusterIdentity is not of type Service Principal

### ISSUE THREAD

**Issue by alon-z** [kubernetes-sigs/cluster-api-provider-azure#2107]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Follow quick start guide with a cluster on AWS and using https://capz.sigs.k8s.io/topics/multitenancy.html#manual-service-principal-identity guide to support a cluster without `aad-pod-identity`

Our AzureClusterIdentity:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: XXX-XXX-XX-XX-XXXX
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: XXX-XXX-XX-XX-XXXX
  type: ManualServicePrincipal
```

Logged error:
```
failed to create scope: AzureClusterIdentity is not of type Service Principal
sigs.k8s.io/cluster-api-provider-azure/azure/scope.NewAzureClusterCredentialsProvider
	/workspace/azure/scope/identity.go:93
sigs.k8s.io/cluster-api-provider-azure/azure/scope.NewClusterScope
	/workspace/azure/scope/cluster.go:72
sigs.k8s.io/cluster-api-provider-azure/controllers.(*AzureClusterReconciler).Reconcile
. . .
```

**What did you expect to happen:**
A management cluster without `aad-pod-identity` deployed on AWS that can create workload clusters using the ManualServicePrincipal identity feature.

**Anything else you would like to add:**
Using version 1.1.2 (current latest)

Feature PR:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1514
Similar rotten issue:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1762
The line in issue:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/94fb411d2d90541ba2020aae969ce2fadf57d451/azure/scope/identity.go#L92-L94

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
