### ISSUE TITLE
`userAssignedIdentityID` in `azure.json` is wrong when using user assinged MSI

### ISSUE THREAD

**Issue by ArchangelSDY** [kubernetes-sigs/cluster-api-provider-azure#2164]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
1. Create a control plane `AzureMachineTemplate` that specifies `userAssignedIdentities`. For example,

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: foo-control-plane
  namespace: foo
spec:
  template:
    spec:
      dataDisks:
      - diskSizeGB: 256
        lun: 0
        nameSuffix: etcddisk
      identity: UserAssigned
      osDisk:
        diskSizeGB: 128
        osType: Linux
      sshPublicKey: 
      userAssignedIdentities:
      - providerID: /subscriptions/...
      - providerID: /subscriptions/...
      vmSize: Standard_F4s
```
2. Check the generated `azure.json` on control plane nodes. The `userAssignedIdentityID` looks like:

```json
{
    "userAssignedIdentityId": "/subscriptions/..."
}
```

**What did you expect to happen:**
There are two issues here:
* It should be `userAssignedIdentityID` rather than `userAssignedIdentityId`
* The value should be a **client id** (GUID) of the MSI. Not an **ARM resource ID** per cloud provider doc: https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
* Bug 1 location:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c3d1ef191f8203adba1a58e920545f297f80037a/controllers/helpers.go#L373
* Bug 2 location:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/c3d1ef191f8203adba1a58e920545f297f80037a/controllers/azurejson_machine_controller.go#L184-L188

**Environment:**

- cluster-api-provider-azure version: v1.1.2
- Kubernetes version: (use `kubectl version`): 1.22
- OS (e.g. from `/etc/os-release`): ubuntu 20.04
