### ISSUE TITLE
Same Subnet for control plane and node networks

### ISSUE THREAD

**Issue by BDworak** [kubernetes-sigs/cluster-api-provider-azure#2202]
/kind feature

**Describe the solution you'd like**
1. Allow for both control plane and worker machines to be deployed to the same subnet.

Example(AzureCluster CRD, networkSpec):
```
subnets:
    - name: Single-Subnet
      role: control-plane
    - name: Single-Subnet
      role: node
```
 
2. (optional)For added customization, allow for IP ranges within an existing subnet to be specified to carve the subnet outside of traditional CIDR blocks. 

Example(AzureCluster CRD, networkSpec. origin network is 10.10.10.0/24):
```
subnets:
    - name: Single-Subnet
      role: control-plane
      ipRange: 10.10.10.1 - 10.10.10.10
    - name: Single-Subnet
      role: node
      ipRange: 10.10.10.11 - 10.10.10.254
```

**Anything else you would like to add:**
When deploying K8s clusters, we find that usually the control-plane network is disproportionately smaller than the node network (3-5 machines for control plane on average). When deploying into an existing /24 network, the current implementation does not allow you finer grained control of the network deployment/configuration. In today's model, deploying into the /24 would mean creating two /25 subnets and reserving 127 IP addresses for the control plane (which is excessive to the extreme) and 127 addresses for the nodes (which could eventually be constraining). 

**Environment:**

- cluster-api-provider-azure version: 1.2.0
- Kubernetes version: (use `kubectl version`): 1.23.5 
- OS (e.g. from `/etc/os-release`):  N/A. Azure network feature
