### ISSUE TITLE
Add AzureMachine condition when userAssignedIdentity is missing from the VM

### ISSUE THREAD

**Issue by desek** [kubernetes-sigs/cluster-api-provider-azure#2319]
/kind bug

**What steps did you take and what happened:**

Deployed an `AzureMachine` via `AzureMachineTemplate` with:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {name}
  namespace: {namespace}
spec:
  template:
    spec:
      vmSize: Standard_DS3_v2
      osDisk:
        diskSizeGB: 128
        osType: Linux
        cachingType: ReadOnly
      dataDisks:
      - diskSizeGB: 256
        lun: 0
        nameSuffix: etcddisk
        managedDisk:
          storageAccountType: StandardSSD_LRS
      sshPublicKey: {sshPublicKey}
      identity: UserAssigned
      userAssignedIdentities:
        - providerID: azure:///subscriptions/{subscription_id}/resourceGroups/{resource_group_name}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{managed_indentity_name}
```

On deployment the pre-created user-assigned identity gets attached to the VM's.
When removing the attachment the managed identity doesn't automatically get re-attached.

**What did you expect to happen:**

The `capz-controller` should reconcile the desired state by re-attaching the managed identity.

**Environment:**

- cluster-api-provider-azure version: v1.3.1
- Kubernetes version: (use `kubectl version`): 1.22.8
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS (Focal Fossa)
