### ISSUE TITLE
Azure load balancer ignores KubeadmControlPlanelocalAPIEndpoint bindPort configuration

### ISSUE THREAD

**Issue by BDworak** [kubernetes-sigs/cluster-api-provider-azure#2332]
/kind bug

**What steps did you take and what happened:**
When deploying a Capi cluster, the KubeadmControlPlane CRD supports changing the apiserver port by setting the bindPort under the localAPIEndpoint. This will modify the apiserver deployment and make it run on the port defined in the bindPort: field. 

```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: my-capz-control-plane
  namespace: my-cluster-capz
spec:
  kubeadmConfigSpec:
   ---- Snipped ----
    initConfiguration:
      localAPIEndpoint:
        bindPort: 443
   ---- Snipped ----
```

When spinning up an Azure Cluster, with load balancer type ``Internal``, the load balancer will spin up and be configured to point to port 6443 and does not take into account that the apiserver is running on custom configured port. 

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: my-capz
  namespace: my-cluster-capz
spec:
     ---- Snipped ----
  networkSpec:
    apiServerLB:
      name: my-capz-internal-lb
      type: Internal
      frontendIPs:
        - name: apiserver-frontend
          privateIP: 10.10.10.10
   ---- Snipped ----
```

**What did you expect to happen:**
This can be fixed in 2 different ways
1. (ideal) The AzureCluster resource is aware of the bindPort configuration and spins up a load balancer pointing towards the bindPort configured in the KubeadmControlPlane. 
2. (best configuration control) Allow for the the frontendIPs object to accept a port: field to configure the custom port for the apiserver. 

**Environment:**

- cluster-api-provider-azure version: 1.2.0
- Kubernetes version: (use `kubectl version`): 1.23.5 
- OS (e.g. from `/etc/os-release`): N/A
