### ISSUE TITLE
controlplane-vm-0 bootstrap failed, trying to connect api server through internal lb ip?

### ISSUE THREAD

**Issue by mogliang** [kubernetes-sigs/cluster-api-provider-azure#2434]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried to follow https://capz.sigs.k8s.io/topics/api-server-endpoint.html to setup cluster with internal LB, peering with mgmt cluster. However, failed on 1st cp vm bootstrap. 

SSH and check cloud init log, shows bootstrap timeout
check kubelet journalctl, shows strange thing, the apiserver dns are resolved to LB internal ip, which i believe inaccessible from internal LB backend pool node. sample log:

```
k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: Get "https://apiserver.qliang-capi-cx6.capz.io:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp **10.243.0.100**:6443
```

**What did you expect to happen:**
cluster created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
mgmt cluster vnet cidr: 10.240.0.0/16
azureCluster def:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: qliang-capi-cx6
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: westus
  networkSpec:
    subnets:
    - name: control-plane-subnet
      cidrBlocks: 
        - 10.243.0.0/24
      role: control-plane
    - name: node-subnet
      natGateway:
        name: node-natgateway
      cidrBlocks: 
        - 10.243.1.0/24
      role: node
    vnet:
      name: qliang-capi-cx6-vnet
      cidrBlocks: 
        - 10.243.0.0/16
      peerings:
        - resourceGroup: qliang-capi
          remoteVnetName: qliang-capi-vnet
    apiServerLB:
      type: Internal
      frontendIPs:
        - name: lb-private-ip-frontend
          privateIP: 10.243.0.100
  resourceGroup: qliang-capi-cx6
  subscriptionID: b9e38f20-7c9c-4497-a25d-1a0c5eef2108
```

**Environment:**

- cluster-api-provider-azure version:  clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.4", GitCommit:"1c3a1526f101d4b07d2eec757fe75e8701cf6212", GitTreeState:"clean", BuildDate:"2022-06-03T17:11:09Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version: (use `kubectl version`): 1.23.3
- OS (e.g. from `/etc/os-release`): 20.04.3 LTS (Focal Fossa)
