### ISSUE TITLE
Allow configuration of Spot instance Eviction Policy

### ISSUE THREAD

**Issue by desek** [kubernetes-sigs/cluster-api-provider-azure#2570]
> ⚠️ Cluster API Azure maintainers can ask to turn an issue-proposal into a [CAEP](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/YYYYMMDD-template.md) when necessary. This is to be expected for large changes that impact multiple components, breaking changes, or new large features.

***Goals***
1. Enable configuration of spot instance eviction policy 
2. Enable use of spot instances with ephemeral disk

***Non-Goals/Future Work***
1. Non-Goal 1
1. Non-Goal 2

**User Story**

As an operator I would like to be able to configure the eviction policy (Deallocate or Delete) of my spot instances for being able to use spot instances together with ephemeral disks which requires eviction policy to be Delete.

**Detailed Description**

Extend the `AzureMachineTemplate` resource with the property `spec.template.spec.spotVMOptions.evictionPolicy` that allows the values `Deallocate` and `Delete` and has a default value of `Deallocate`.

Example:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: spot
spec:
  template:
    spec:
      vmSize: Standard_DS3_v2
      acceleratedNetworking: true
      enableIPForwarding: true
      osDisk:
        osType: linux
        diskSizeGB: 128
        cachingType: ReadOnly
        diffDiskSettings:
          option: Local
      spotVMOptions:
        maxPrice: -1
        evictionPolicy: Delete
      sshPublicKey: <base64>
```

**Contract changes [optional]**

[Describe contract changes between Cluster API Azure Provider controllers, if applicable.]

**Data model changes [optional]**

Changes the model of [AzureMachine](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremachine_types.go) with an additional property with a default value.

/kind proposal
