### ISSUE TITLE
AzureMachinePool Ephemeral OSDisk not working

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#2577]
/kind bug

**What steps did you take and what happened:**
Following config:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: st-005
  namespace: supplier-azure
  annotations:
    cluster.x-k8s.io/externally-managed-replicas: "true"
spec:
  clusterName: azure
  minReadySeconds: 0
  replicas: 1
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: st-005
      clusterName: azure-eu-v2
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachinePool
        name: st-005
      version: v1.23.4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: st-005
  namespace: supplier-azure
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  location: westeurope
  template:
    image:
      sharedGallery:
        gallery: gallery
        name: linux-capi
        offer: OfferName
        resourceGroup: rg
        subscriptionID: ID
        sku: SKU
        version: 0.0.5
    osDisk:
      cachingType: ReadOnly
      diskSizeGB: 150
      osType: Linux
      diffDiskSettings:
        option: Local # ephemeral OS disk
    vmSize: Standard_F16s_v2
  identity: None
  additionalTags:
    cluster-autoscaler-enabled: "true"
    cluster-autoscaler-name: "azure"
    min: "0"
    max: "20"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  name: st-005
  namespace: azure
spec:
  files:
    - contentFrom:
        secret:
          key: worker-node-azure.json
          name: st-005-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
  format: cloud-config
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        azure-container-registry-config: /etc/kubernetes/azure.json
        cloud-config: /etc/kubernetes/azure.json
        cloud-provider: azure
      name: '{{ ds.meta_data["local_hostname"] }}'
```

Fails to create with error:
```
capz-controller-manager-656bfc5c9f-sm9rk manager E0819 11:32:45.359357       1 controller.go:317] controller/azuremachinepool "msg"="Reconciler error" "error"="failed to reconcile AzureMachinePool service scalesets: failed to start creating VMSS: cannot create VMSS: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"NotSupported\" Message=\"VMs and VM Scale Set Instances using an ephemeral OS disk support only Readonly caching.\"" "name"="st-005" "namespace"="azure" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AzureMachinePool" 
```

**What did you expect to happen:**
Config works and VMSS gets created accordingly.

**Anything else you would like to add:**
Code in question does not set the CachingType on the VMSS Spec:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/b2abf8c89c5eebd251a5915d3309eeeb3de534e1/azure/services/scalesets/scalesets.go#L611

compared to

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/b2abf8c89c5eebd251a5915d3309eeeb3de534e1/azure/services/scalesets/scalesets.go#L611

**Environment:**

- cluster-api-provider-azure version: v1.4.1
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): linux
