### ISSUE TITLE
windows cluster with cloud-provider: external does not work

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#2591]
/kind bug

**What steps did you take and what happened:**
I created a CAPZ cluster with windows machine pools inside and `cloud-provider: external`. 
I deployed the cloud provider using [the official helm chart](https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/helm/cloud-provider-azure). 

The Daemonset for cloud-node-manager-windows is not able to reach the metadata endpoint and therefore windows nodes always have the Taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`. 

<details>
  <summary>Cluster resources YAML</summary>

  ```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: calico
    ccm: "external"
  name: mycluster
  namespace: mynamespace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ctrl-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureCluster
    name: mycluster
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ctrl-plane
  namespace: mynamespace
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: external
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
        timeoutForControlPlane: 20m0s
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "false"
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: external
          cluster-name: mycluster
        extraVolumes:
        - hostPath: /etc/kubernetes/azure.json
          mountPath: /etc/kubernetes/azure.json
          name: cloud-config
          readOnly: true
      dns: {}
      etcd:
        local:
          dataDir: /var/lib/etcddisk/etcd
          extraArgs:
            quota-backend-bytes: "8589934592"
      networking: {}
      scheduler: {}
    diskSetup:
      filesystems:
      - device: /dev/disk/azure/scsi1/lun0
        extraOpts:
        - -E
        - lazy_itable_init=1,lazy_journal_init=1
        filesystem: ext4
        label: etcd_disk
      - device: ephemeral0.1
        filesystem: ext4
        label: ephemeral0
        replaceFS: ntfs
      partitions:
      - device: /dev/disk/azure/scsi1/lun0
        layout: true
        overwrite: false
        tableType: gpt
    files:
    - contentFrom:
        secret:
          key: control-plane-azure.json
          name: ctrl-plane-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
    format: cloud-config
    initConfiguration:
      localAPIEndpoint: {}
      nodeRegistration:
        kubeletExtraArgs:
          azure-container-registry-config: /etc/kubernetes/azure.json
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: external
        name: '{{ ds.meta_data["local_hostname"] }}'
    joinConfiguration:
      discovery: {}
      nodeRegistration:
        kubeletExtraArgs:
          azure-container-registry-config: /etc/kubernetes/azure.json
          cloud-config: /etc/kubernetes/azure.json
          cloud-provider: external
        name: '{{ ds.meta_data["local_hostname"] }}'
    mounts:
    - - LABEL=etcd_disk
      - /var/lib/etcddisk
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureMachineTemplate
      name: ctrl-plane
    metadata: {}
  replicas: 1
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  version: v1.24.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: mycluster
  namespace: mynamespace
spec:
  azureEnvironment: AzurePublicCloud
  bastionSpec: {}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: mycluster-identity
  location: westeurope
  networkSpec:
    subnets:
    - cidrBlocks:
      - 10.0.0.0/16
      name: control-plane-subnet
      role: control-plane
    - cidrBlocks:
      - 10.1.0.0/16
      name: node-subnet
      role: node
    vnet:
      cidrBlocks:
      - 10.0.0.0/8
      name: mycluster-vnet
  resourceGroup: mycluster
  subscriptionID: ${SUBSCRIPTION_ID}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: ctrl-plane
  namespace: mynamespace
spec:
  template:
    metadata: {}
    spec:
      dataDisks:
        - cachingType: ReadWrite
          diskSizeGB: 256
          lun: 0
          nameSuffix: etcddisk
      identity: None
      image:
        sharedGallery:
          gallery: ${GALLERY}
          name: ${NAME}
          offer: ${OFFER}
          resourceGroup: ${RESOURCE_GROUP}
          subscriptionID: ${SUBSCRIPTION_ID}
          sku: ${SKU}
          version: ${VERSION}
      osDisk:
        cachingType: ReadOnly
        diskSizeGB: 150
        osType: Linux
        diffDiskSettings:
          option: Local # ephemeral OS disk
      sshPublicKey: ""
      vmSize: Standard_D4ads_v5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: mycluster-identity
  namespace: mynamespace
spec:
  allowedNamespaces:
    list:
      - mynamespace
  clientID: ${CLIENT_ID}
  clientSecret:
    name: mycluster-identity-secret
    namespace: mynamespace
  tenantID: ${TENANT_ID}
  type: ManualServicePrincipal
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: worker
  namespace: mynamespace
spec:
  clusterName: mycluster
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels: null
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: worker
      clusterName: mycluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate
        name: worker
      version: v1.24.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: worker
  namespace: mynamespace
spec:
  template:
    metadata: {}
    spec:
      identity: None
      image:
        sharedGallery:
          gallery: ${GALLERY}
          name: ${NAME}
          offer: ${OFFER}
          resourceGroup: ${RESOURCE_GROUP}
          subscriptionID: ${SUBSCRIPTION_ID}
          sku: ${SKU}
          version: ${VERSION}
      osDisk:
        cachingType: ReadOnly
        diskSizeGB: 150
        osType: Linux
        diffDiskSettings:
          option: Local # ephemeral OS disk
      sshPublicKey: ""
      vmSize: Standard_D8ads_v5
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: worker
  namespace: mynamespace
spec:
  template:
    spec:
      files:
        - contentFrom:
            secret:
              key: worker-node-azure.json
              name: worker-azure-json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
      format: cloud-config
      joinConfiguration:
        discovery: {}
        nodeRegistration:
          kubeletExtraArgs:
            azure-container-registry-config: /etc/kubernetes/azure.json
            cloud-config: /etc/kubernetes/azure.json
            cloud-provider: external
            node-labels: "node.helio.exchange/role=worker"
          name: '{{ ds.meta_data["local_hostname"] }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: win
  namespace: mynamespace
  annotations:
    cluster.x-k8s.io/replicas-managed-by-autoscaler: "true"
spec:
  clusterName: mycluster
  minReadySeconds: 0
  replicas: 1
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: win
      clusterName: mycluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachinePool
        name: win
      version: v1.24.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: win
  namespace: mynamespace
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  location: westeurope
  template:
      image:
        sharedGallery:
          gallery: ${GALLERY}
          name: ${WIN_NAME}
          offer: ${WIN_OFFER}
          resourceGroup: ${RESOURCE_GROUP}
          subscriptionID: ${SUBSCRIPTION_ID}
          sku: ${WIN_SKU}
          version: ${WIN_VERSION}
    osDisk:
      cachingType: ReadOnly
      diskSizeGB: 750
      osType: Windows
      diffDiskSettings:
        option: Local # ephemeral OS disk
    sshPublicKey: ""
    vmSize: Standard_D96as_v4
    spotVMOptions: {}
  identity: None
  additionalTags:
    cluster-autoscaler-enabled: "true"
    cluster-autoscaler-name: "mycluster"
    min: "0"
    max: "5"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfig
metadata:
  name: win
  namespace: mynamespace
spec:
  files:
    - contentFrom:
        secret:
          key: worker-node-azure.json
          name: win-azure-json
      owner: root:root
      path: c:/k/azure.json
      permissions: "0644"
    - content: |-
        Add-MpPreference -ExclusionProcess C:/opt/cni/bin/calico.exe
        Add-MpPreference -ExclusionProcess C:/opt/cni/bin/calico-ipam.exe
      path: C:/defender-exclude-calico.ps1
      permissions: "0744"
  format: cloud-config
  joinConfiguration:
    discovery: {}
    nodeRegistration:
      criSocket: npipe:////./pipe/containerd-containerd
      kubeletExtraArgs:
        azure-container-registry-config: c:/k/azure.json
        cloud-config: c:/k/azure.json
        cloud-provider: external
        feature-gates: WindowsHostProcessContainers=true
        v: "2"
        windows-priorityclass: ABOVE_NORMAL_PRIORITY_CLASS
        volume-plugin-dir: "C:\\k\\volumeplugins"
      name: '{{ ds.meta_data["local_hostname"] }}'
  postKubeadmCommands:
    - nssm set kubelet start SERVICE_AUTO_START
    - powershell C:/defender-exclude-calico.ps1
```
</details>

Helm chart values changed only the following:
```yaml
          parameters:
            - name: infra.clusterName
              value: "{{name}}"
            - name: cloudNodeManager.waitRoutes
              value: "true"
```

When deploying this, a timeout happens after a while:
```
cloud-node-manager-windows-5ml4w cloud-node-manager 	panic: failed to initialize node NODENAME at cloudprovider: failed to set node provider id: Get "http://169.254.169.254/metadata/instance?api-version=2021-10-01&format=json": dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
cloud-node-manager-windows-5ml4w cloud-node-manager 
```

I tried to switch to hostProcess/hostNetwork for cloud-node-manager-windows but I wasn't sure what the proper way of propagating a correct kubeconfig was.

<details>
  <summary>Hostprocess cloud-node-manager-windows</summary>
  
  ```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-node-manager-windows
  namespace: kube-system
  labels:
    component: cloud-node-manager
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: cloud-node-manager-windows
  template:
    metadata:
      labels:
        k8s-app: cloud-node-manager-windows
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cloud-node-manager
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: "Exists"
        effect: NoExecute
      - operator: "Exists"
        effect: NoSchedule
      containers:
      - name: cloud-node-manager
        image: {{ template "image.cloudNodeManager" . | required "you must use a supported version of Kubernetes or provide cloudNodeManager.imageRepository, cloudNodeManager.imageName, and cloudNodeManager.imageTag values" }}
        imagePullPolicy: {{ .Values.cloudNodeManager.imagePullPolicy }}
        command: ["cloud-node-manager.exe"]
        workingDir: "$env:CONTAINER_SANDBOX_MOUNT_POINT/"
        args:
          - --node-name=$(NODE_NAME)
          {{- if hasKey .Values.cloudNodeManager "cloudConfig" }}
          - "--cloud-config={{ .Values.cloudNodeManager.cloudConfig }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "kubeAPIBurst" }}
          - "--kube-api-burst={{ .Values.cloudNodeManager.kubeAPIBurst }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "kubeAPIContentType" }}
          - "--kube-api-content-type={{ .Values.cloudNodeManager.kubeAPIContentType }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "kubeAPIQPS" }}
          - "--kube-api-qps={{ .Values.cloudNodeManager.kubeAPIQPS }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "kubeconfig" }}
          - "--kubeconfig={{ .Values.cloudNodeManager.kubeconfig }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "master" }}
          - "--master={{ .Values.cloudNodeManager.master }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "minResyncPeriod" }}
          - "--min-resync-period={{ .Values.cloudNodeManager.minResyncPeriod }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "nodeStatusUpdateFrequency" }}
          - "--node-status-update-frequency={{ .Values.cloudNodeManager.nodeStatusUpdateFrequency }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "useInstanceMetadata" }}
          - "--use-instance-metadata={{ .Values.cloudNodeManager.useInstanceMetadata }}"
          {{- end }}
          {{- if hasKey .Values.cloudNodeManager "waitRoutes" }}
          - "--wait-routes={{ .Values.cloudNodeManager.waitRoutes }}"
          {{- end }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: {{ .Values.cloudNodeManager.containerResourceManagement.requestsCPUWin }}
            memory: {{ .Values.cloudNodeManager.containerResourceManagement.requestsMemWin }}
          limits:
            cpu: {{ .Values.cloudNodeManager.containerResourceManagement.limitsCPUWin }}
            memory: {{ .Values.cloudNodeManager.containerResourceManagement.limitsMemWin }}
  ```
</details>

When using this, the following is logged:
```
cloud-node-manager-windows-8scmm cloud-node-manager W0823 11:48:33.679405    5288 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
cloud-node-manager-windows-8scmm cloud-node-manager W0823 11:48:33.703905    5288 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
cloud-node-manager-windows-8scmm cloud-node-manager invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

I believe this could be related to #2132.
I needed to patch [RBAC for the helm chart](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2210) too. 

**What did you expect to happen:**
external cloud-provider-azure works for windows clusters too.

**Environment:**

- cluster-api-provider-azure version: v1.4.1
- Kubernetes version: (use `kubectl version`): v1.24.3
- OS (e.g. from `/etc/os-release`): linux/windows mixed

**Comment by CecileRobertMichon** [comment]
@jackfrancis @lzhecheng @marosset any ideas on this one?

cc @Jont828

**Comment by marosset** [comment]
> I tried to switch to hostProcess/hostNetwork for cloud-node-manager-windows but I wasn't sure what the proper way of propagating a correct kubeconfig was.

In K8s v1.26 (and with containerd v1.7) you'l be able to use `InClusterConfig()` for this.
Fow now we do in CAPZ we copy values out of the kubeadm config and use that.
https://github.com/kubernetes-sigs/sig-windows-tools/blob/9b61b4510ea0a76735ab53a67b4c86d5d3dc478d/hostprocess/calico/install/calico-install.ps1#L13-L22
It is pretty hacky for now :(

**Comment by monianshouhou** [comment]
We can build windows cluster with all nodes and pods (including CCM and CNM) ready by setting the following environment variables and running ./scripts/ci-entrypoint.sh:
https://github.com/kubernetes/test-infra/blob/0931e16cae94200f532e242bffe0514c401978f0/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L481-L496
Could you give it a try to incorporate your change into the yaml file in the capz ./templates/test/ci/cluster-template-prow-ci-version.yaml and create cluster via the way mentioned above?

**Comment by mweibel** [comment]
@marosset yeah that's what I saw. Pretty hacky indeed but I guess the only other option is to use the in-tree one :(

@monianshouhou thanks for the pointers! Will try. I'm not yet sure which parts are all collected together (haven't examined the script yet), but I noticed one difference in the external cloud provider test yaml:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml#L526

The windows MachineDeployment does use the in-tree cloud-provider while the linux control plane and worker nodes use the external one.

**Comment by monianshouhou** [comment]
> @marosset yeah that's what I saw. Pretty hacky indeed but I guess the only other option is to use the in-tree one :(
> 
> @monianshouhou thanks for the pointers! Will try. I'm not yet sure which parts are all collected together (haven't examined the script yet), but I noticed one difference in the external cloud provider test yaml: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/test/ci/cluster-template-prow-external-cloud-provider-ci-version.yaml#L526
> 
> The windows MachineDeployment does use the in-tree cloud-provider while the linux control plane and worker nodes use the external one.

@CecileRobertMichon Do you know why ```cloud-provider: azure``` only for windows?

**Comment by mweibel** [comment]
curious, I started the recommended test deployment. 


<details>
  <summary>Env used (redacted)</summary>
  
  ```bash
export TEST_CCM=true
export AZURE_LOADBALANCER_SKU=standard
export CONTROL_PLANE_MACHINE_COUNT=1
export TEST_WINDOWS=true
export WINDOWS_FLAVOR=containerd-2022
export KUBERNETES_VERSION=latest
export WORKER_MACHINE_COUNT=0
export CLUSTER_PROVISIONING_TOOL=capz

export AZURE_SUBSCRIPTION_ID="REDACTED"
export AZURE_TENANT_ID="REDACTED"
export AZURE_CLIENT_ID="REDACTED"
export AZURE_CLIENT_SECRET='REDACTED'
export AZURE_LOCATION="westeurope"

export AZURE_STORAGE_ACCOUNT=REDACTED
export AZURE_STORAGE_KEY="REDACTED"

export REGISTRY=REDACTED
  ```
</details>

The `KubeadmConfigTemplate` for windows has (as expected) the in-tree `cloud-provider` configured:

```yaml
      format: cloud-config
      joinConfiguration:
        discovery: {}
        nodeRegistration:
          criSocket: npipe:////./pipe/containerd-containerd
          kubeletExtraArgs:
            azure-container-registry-config: c:/k/azure.json
            cloud-config: c:/k/azure.json
            cloud-provider: azure
            feature-gates: WindowsHostProcessContainers=true
            v: "2"
            windows-priorityclass: ABOVE_NORMAL_PRIORITY_CLASS
          name: '{{ ds.meta_data["local_hostname"] }}'
```

The windows nodes seem to have been initialized correctly:

```yaml
```

The logs of both windows nodes (take well note of the time difference between `Started cloud-node-manager` and `Error reconciling node address` (~5 minutes, I guess that's a configurerd timeout):
```
+ cloud-node-manager-windows-9kq2t › cloud-node-manager
cloud-node-manager-windows-9kq2t cloud-node-manager W0825 11:05:34.277937    5312 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
cloud-node-manager-windows-9kq2t cloud-node-manager I0825 11:05:34.665541    5312 nodemanager.go:104] Version: v1.24.0-417-g6469e6e70
cloud-node-manager-windows-9kq2t cloud-node-manager I0825 11:05:34.665541    5312 nodemanager.go:105] NodeName: capz-8a3h-wprtr
cloud-node-manager-windows-9kq2t cloud-node-manager I0825 11:05:34.678387    5312 nodemanager.go:140] Sending events to api server.
cloud-node-manager-windows-9kq2t cloud-node-manager I0825 11:05:34.680514    5312 nodemanager.go:156] Started cloud-node-manager
+ cloud-node-manager-windows-bbjzb › cloud-node-manager
cloud-node-manager-windows-bbjzb cloud-node-manager W0825 11:05:36.019015    5564 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
cloud-node-manager-windows-bbjzb cloud-node-manager I0825 11:05:36.311863    5564 nodemanager.go:104] Version: v1.24.0-417-g6469e6e70
cloud-node-manager-windows-bbjzb cloud-node-manager I0825 11:05:36.311863    5564 nodemanager.go:105] NodeName: capz-8a3h-nj5l6
cloud-node-manager-windows-bbjzb cloud-node-manager I0825 11:05:36.320794    5564 nodemanager.go:140] Sending events to api server.
cloud-node-manager-windows-bbjzb cloud-node-manager I0825 11:05:36.321320    5564 nodemanager.go:156] Started cloud-node-manager
cloud-node-manager-windows-9kq2t cloud-node-manager E0825 11:10:55.730683    5312 nodemanager.go:195] Error reconciling node address for node "capz-8a3h-wprtr", err: Error getting node addresses for node "capz-8a3h-wprtr": error fetching node by name capz-8a3h-wprtr: Get "http://169.254.169.254/metadata/instance?api-version=2021-10-01&format=json": dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
cloud-node-manager-windows-bbjzb cloud-node-manager E0825 11:10:57.407063    5564 nodemanager.go:195] Error reconciling node address for node "capz-8a3h-nj5l6", err: Error getting node addresses for node "capz-8a3h-nj5l6": error fetching node by name capz-8a3h-nj5l6: Get "http://169.254.169.254/metadata/instance?api-version=2021-10-01&format=json": dial tcp 169.254.169.254:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

One node describe:
```
 $ k describe no capz-8a3h-nj5l6
Name:               capz-8a3h-nj5l6
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D2s_v3
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=westeurope
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=capz-8a3h-nj5l6
                    kubernetes.io/os=windows
                    node.kubernetes.io/instance-type=Standard_D2s_v3
                    node.kubernetes.io/windows-build=10.0.17763
                    topology.kubernetes.io/region=westeurope
                    topology.kubernetes.io/zone=0
Annotations:        cluster.x-k8s.io/cluster-name: capz-8a3hcc
                    cluster.x-k8s.io/cluster-namespace: default
                    cluster.x-k8s.io/machine: capz-8a3hcc-md-win-79854c4679-dbr9b
                    cluster.x-k8s.io/owner-kind: MachineSet
                    cluster.x-k8s.io/owner-name: capz-8a3hcc-md-win-79854c4679
                    kubeadm.alpha.kubernetes.io/cri-socket: npipe:////./pipe/containerd-containerd
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.1.0.4/16
                    projectcalico.org/IPv4VXLANTunnelAddr: 192.168.107.193
                    projectcalico.org/VXLANTunnelMACAddr: 00:15:5d:0b:2f:a5
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 25 Aug 2022 13:03:37 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  capz-8a3h-nj5l6
  AcquireTime:     <unset>
  RenewTime:       Thu, 25 Aug 2022 13:14:31 +0200
```

The taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` is not there. I assume (until I test it), the reason for this is because the `cloud-provider` argument is not set to external.
