### ISSUE TITLE
AzureCluster object gets updated continuously while using cluster class

### ISSUE THREAD

**Issue by sonasingh46** [kubernetes-sigs/cluster-api-provider-azure#2659]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I created a cluster using cluster class and observed that AzureCluster object gets updated continuously by the topology controller. 
Pasting the kubectl describe output for Cluster object: 
```
Events:
  Type    Reason          Age                 From              Message
  ----    ------          ----                ----              -------
  Normal  TopologyCreate  35h                 topology/cluster  Created "AzureCluster/my-cluster-vt6k7"
  Normal  TopologyCreate  35h                 topology/cluster  Created "AzureMachineTemplate/my-cluster-control-plane-9zrlq"
  Normal  TopologyCreate  35h                 topology/cluster  Created "KubeadmControlPlane/my-cluster-d4tcd"
  Normal  TopologyUpdate  35h                 topology/cluster  Updated "Cluster/my-cluster"
  Normal  TopologyCreate  35h                 topology/cluster  Created "AzureMachineTemplate/my-cluster-md-0-infra-sbzjw"
  Normal  TopologyCreate  35h                 topology/cluster  Created "KubeadmConfigTemplate/my-cluster-md-0-bootstrap-hs8lm"
  Normal  TopologyCreate  35h                 topology/cluster  Created "MachineDeployment/my-cluster-md-0-tp2mt"
  Normal  TopologyUpdate  35h                 topology/cluster  Updated "MachineDeployment/my-cluster-md-0-tp2mt"
  Normal  TopologyUpdate  83s (x93 over 35h)  topology/cluster  Updated "AzureCluster/my-cluster-vt6k7"
  ```
  
  Also the capi manager is flooded with the following logs: 
  ```
  I0919 08:02:03.428112       1 reconcile_state.go:300] "Patching AzureCluster/my-cluster-vt6k7" controller="topology/cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" cluster="default/my-cluster" namespace="default" name="my-cluster" reconcileID=5d9a1586-5dcf-466f-912c-3d59afd69998 object groupVersion="infrastructure.cluster.x-k8s.io/v1beta1" object kind="AzureCluster" object="my-cluster-vt6k7"
```

One interesting observation is that I compared two versions of the same AzureCluster  object and observed that only `resourceVersion` and `generation` fields had changed. But this is just because both the controllers are fighting ( capi manager and capz manager ) to update the subnet spec and it is so quick that we may not be able to see the diff b/w last two consecutive updates by the two managers. So I stopped the reconciliation on the AzureCluster object to understand this. Here is what happens: 
- CAPI manager requests a SSA causing the AzureClusterTemplate to get updated. 
- CAPZ manager patches the subnet spec to update the `name` field of the subnet. 
- CAPI manager again requests a SSA assuming the spec has changed. 
- This oscillation continues. 

Here is the spec after capi manager SSA update: 

```
    subnets:
    - cidrBlocks:
      - 10.0.0.0/16
      name: my-cluster-vt6k7-controlplane-subnet
      natGateway:
        ip:
          name: ""
        name: ""
      role: control-plane
      routeTable:
        name: ""
      securityGroup:
        name: my-cluster-vt6k7-controlplane-nsg
    - cidrBlocks:
      - 10.1.0.0/16
      name: my-cluster-vt6k7-node-subnet-1
      natGateway:
        ip:
          name: ""
        name: ""
      role: node
      routeTable:
        name: my-cluster-vt6k7-node-routetable
      securityGroup:
        name: my-cluster-vt6k7-node-nsg
        
```

Here is the spec after the capz manager patch on subnet spec: 

```
subnets:
    - cidrBlocks:
      - 10.0.0.0/16
      name: my-cluster-vt6k7-controlplane-subnet
      natGateway:
        ip:
          name: ""
        name: ""
      role: control-plane
      routeTable:
        name: ""
      securityGroup:
        name: my-cluster-vt6k7-controlplane-nsg
    - cidrBlocks:
      - 10.1.0.0/16
      name: my-cluster-vt6k7-node-subnet-1
      natGateway:
        ip:
          name: ""
        name: ""
      role: node
      routeTable:
        name: my-cluster-vt6k7-node-routetable
      securityGroup:
        name: my-cluster-vt6k7-node-nsg
  ```
   

**Used the following ClusterClass:** 

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: simple-cc
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: high-availability-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate
        name: control-plane-machine
  workers:
    machineDeployments:
      - class: type1-workers
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: type1-bootstrap
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: AzureMachineTemplate
              name: type1-machine
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterTemplate
      name: my-azurecluster-template
```

**Used the following AzureClusterTemplate:**

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: my-azurecluster-template
spec:
  template:
    spec:
      location: eastus
      subscriptionID: fb7bf8d1-5939-4426-b67c-21f6817439d7
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: mycluster-identity
```

**What did you expect to happen:**

This continuous update of the AzureCluster object should not happen. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Linking a similar issue in CAPA ( https://github.com/kubernetes-sigs/cluster-api/issues/6320 )
Linking the PR in capz that aims to fix this. ( https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2636 )

**Environment:**
- capi version: v1.2.2
- cluster-api-provider-azure version: **main**
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
