### ISSUE TITLE
No sudo access to the control plane VMs

### ISSUE THREAD

**Issue by thiDucTran** [kubernetes-sigs/cluster-api-provider-azure#2733]
/kind bug

Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)? Yes

**What steps did you take and what happened:**
Followed instruction @ https://capz.sigs.k8s.io/topics/ssh-access.html#authentication as shown below.
* can SSH into control plane VM via Public LB IP but is prompted for password when doing `sudo` 

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: thi-test-cilium-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    users:
    - name: thitran
      sshAuthorizedKeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrCLAHg3NgBY1TQYMnFEZ7Uy5Vww+G2Rd3PTSkERPKcd9dyqn3YkZ3FjutVdOAIiW7xV5/CUrxQALy0sPi3t3HtqRcF4Y5sSW+pJORdJF+YPLhu60utHvh1v/K0clEPX76r4/yRDX1IGOVQCcG5rqL9ireTMqpACxp4hhAiNsRU650UJHUpIHGd82/lJmwPvM2VWOb28K/ganaheSTDwAGc9XfQOXKUBEkf0HW0X6d6KdUd5+T0JG4Oz4VzHcY8+4hOwhyguvwQS9LexuSQXnJlEOZhBq3zre2P7qkrNkyYGlu4q5S6V7EOa8tRjHWGRafWHjimErtvCh1rY2ZBgmJauGkzwon8Ru51EJJxrwacZ6vyWKx9FvgGCpa7MCjUaqBW4HG8dunfK1WscWEQM2OI/1KSh74+LBq+gbO85FQr9jrUjYHUOhreibbSkGeKK1nNag0Y+ndGshSiQcB4nbr11NmoU3pVYmnsiUj+c+FfS31wjGZEtrywVU9RGI3lMM="
    files:
    - content: "thitran ALL = (ALL) NOPASSWD: ALL"
      owner: root:root
      path: /etc/sudoers.d/thitran
      permissions: "0440"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: thi-test-cilium-md-0
  namespace: default
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: worker-node-azure.json
            name: thi-test-cilium-md-0-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      - content: "thitran ALL = (ALL) NOPASSWD: ALL"
        owner: root:root
        path: /etc/sudoers.d/thitran
        permissions: "0440"
      users:
      - name: thitran
        sshAuthorizedKeys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrCLAHg3NgBY1TQYMnFEZ7Uy5Vww+G2Rd3PTSkERPKcd9dyqn3YkZ3FjutVdOAIiW7xV5/CUrxQALy0sPi3t3HtqRcF4Y5sSW+pJORdJF+YPLhu60utHvh1v/K0clEPX76r4/yRDX1IGOVQCcG5rqL9ireTMqpACxp4hhAiNsRU650UJHUpIHGd82/lJmwPvM2VWOb28K/ganaheSTDwAGc9XfQOXKUBEkf0HW0X6d6KdUd5+T0JG4Oz4VzHcY8+4hOwhyguvwQS9LexuSQXnJlEOZhBq3zre2P7qkrNkyYGlu4q5S6V7EOa8tRjHWGRafWHjimErtvCh1rY2ZBgmJauGkzwon8Ru51EJJxrwacZ6vyWKx9FvgGCpa7MCjUaqBW4HG8dunfK1WscWEQM2OI/1KSh74+LBq+gbO85FQr9jrUjYHUOhreibbSkGeKK1nNag0Y+ndGshSiQcB4nbr11NmoU3pVYmnsiUj+c+FfS31wjGZEtrywVU9RGI3lMM="
```

**What did you expect to happen:**
Able to `sudo` after `ssh` into control plane VM

**Anything else you would like to add:**
From control plane VM, I can ssh into machine VM and sudo in machine VM fine.

**Environment:**

- cluster-api-provider-azure version:
`k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.2`
`registry.k8s.io/cluster-api-azure/cluster-api-azure-controller:v1.5.1`
- Kubernetes version: (use `kubectl version`)
```bash
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-22T05:25:21Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```bash
thitran@thi-test-cilium-control-plane-s5jlk:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
