### ISSUE TITLE
Default MachinePool spec.replicas=0 default value is invalid

### ISSUE THREAD

**Issue by zioproto** [kubernetes-sigs/cluster-api-provider-azure#2759]
/kind question

Generating the cluster resources with this command:
```
clusterctl generate cluster test --kubernetes-version 1.23.12 --flavor aks
```
By default the `MachinePool` has 0 replicas.

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: pool0
  namespace: default
spec:
  clusterName: test
  replicas: 0
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pool0
      version: 1.23.12
```

The AKS cluster fails with `the value of parameter agentPoolProfile.count is invalid`

The number of replicas can be changed with the env var `WORKER_MACHINE_COUNT`. However the docs dont specify that this env variable is mandatory. https://capz.sigs.k8s.io/topics/managedcluster.html

The docs are a bit confusing because the guidance is:
```
# Kubernetes values
export CLUSTER_NAME="my-cluster"
export WORKER_MACHINE_COUNT=2
export KUBERNETES_VERSION="v1.19.6"
clusterctl init --infrastructure azure
clusterctl generate cluster ${CLUSTER_NAME} --kubernetes-version ${KUBERNETES_VERSION} --flavor aks > cluster.yaml
```
[It seems KUBERNETES_VERSION also dont need command line arguments to be evaluated](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/cmd/util.go#L100). Because the other variables are passed as command line arguments it would be great to make also `WORKER_MACHINE_COUNT` explicit in the docs:

```
clusterctl generate cluster ${CLUSTER_NAME} --kubernetes-version ${KUBERNETES_VERSION} --worker-machine-count=${WORKER_MACHINE_COUNT} --flavor aks > cluster.yaml
```

**What did you expect to happen:**

Why the default template does not have `replicas: 1` ?
Is it the normal behaviour for other providers to deploy with 0 replicas ? Is this an AKS only limit ?

Why the naming `WORKER_MACHINE_COUNT` ?  Should `MACHINE_POOL_REPLICAS` be a more consistent name for this variable ?

**Environment:**

- cluster-api-provider-azure version: v1.5.3
- Kubernetes version: 1.23.12

This was discussed also here:
https://github.com/Azure/aks-engine/issues/2311
