### ISSUE TITLE
sig/azure label does not exist in this repo

### ISSUE THREAD

**Issue by fejta** [kubernetes-sigs/cluster-api-provider-azure#276]
If you want it to, labels are controlled by https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

```yaml
{
 insertId: "nbfzblfolg6ze"  
 jsonPayload: {
  author: "CecileRobertMichon"   
  component: "hook"   
  event-GUID: "09663cc0-e171-11e9-9535-d2d594b8deea"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:119"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["sig/azure"]"   
  org: "kubernetes-sigs"   
  plugin: "owners-label"   
  pr: 275   
  repo: "cluster-api-provider-azure"   
  url: "https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/275"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-09-27T21:52:21.364406344Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-09-27T21:52:17Z"  
}
```
