### ISSUE TITLE
Update clusterctl AKS flavor for easier kubectl apply of multiple templates in the same namespace

### ISSUE THREAD

**Issue by AAkindele** [kubernetes-sigs/cluster-api-provider-azure#2811]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

When following the managed cluster documentation, <https://capz.sigs.k8s.io/topics/managedcluster.html>, everything works as expected when creating the first cluster. The issue starts when a user tries to generate a second cluster template using clusterctl, then kubectl apply to the same namespace. The issues can be resolved by updating MachinePool and AzureManagedMachinePool resources in the template. I believe it would be helpful for newer users if the AKS flavor template was modified to allow the example below to work without having to manually modify the generated yaml file.

Example:

```bash

clusterctl generate cluster cluster-01 --kubernetes-version v1.24.6 --control-plane-machine-count=1 --worker-machine-count=1 --flavor=aks > cluster-01.yaml
clusterctl generate cluster cluster-02 --kubernetes-version v1.24.6 --control-plane-machine-count=1 --worker-machine-count=1 --flavor=aks > cluster-02.yaml

# This works as expected.
kubectl apply -f cluster-01.yaml
# This fails if MachinePool and AzureManagedMachinePool names are not updated.
kubectl apply -f cluster-02.yaml

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Example error message:

```txt

Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.x-k8s.io/v1beta1\",\"kind\":\"MachinePool\",\"metadata\":{\"annotations\":{},\"name\":\"pool0\",\"namespace\":\"default\"},\"spec\":{\"clusterName\":\"cluster-02\",\"replicas\":1,\"template\":{\"metadata\":{},\"spec\":{\"bootstrap\":{\"dataSecretName\":\"\"},\"clusterName\":\"cluster-02\",\"infrastructureRef\":{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta1\",\"kind\":\"AzureManagedMachinePool\",\"name\":\"pool0\"},\"version\":\"v1.24.6\"}}}}\n"}},"spec":{"clusterName":"cluster-02","template":{"spec":{"clusterName":"cluster-02"}}}}
to:
Resource: "cluster.x-k8s.io/v1beta1, Resource=machinepools", GroupVersionKind: "cluster.x-k8s.io/v1beta1, Kind=MachinePool"
Name: "pool0", Namespace: "default"
for: "cluster-02.yaml": error when patching "cluster-02.yaml": admission webhook "validation.machinepool.cluster.x-k8s.io" denied the request: MachinePool.cluster.x-k8s.io "pool0" is invalid: spec.clusterName: Forbidden: field is immutable
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"cluster.x-k8s.io/v1beta1\",\"kind\":\"MachinePool\",\"metadata\":{\"annotations\":{},\"name\":\"pool1\",\"namespace\":\"default\"},\"spec\":{\"clusterName\":\"cluster-02\",\"replicas\":1,\"template\":{\"metadata\":{},\"spec\":{\"bootstrap\":{\"dataSecretName\":\"\"},\"clusterName\":\"cluster-02\",\"infrastructureRef\":{\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta1\",\"kind\":\"AzureManagedMachinePool\",\"name\":\"pool1\"},\"version\":\"v1.24.6\"}}}}\n"}},"spec":{"clusterName":"cluster-02","template":{"spec":{"clusterName":"cluster-02"}}}}
to:
Resource: "cluster.x-k8s.io/v1beta1, Resource=machinepools", GroupVersionKind: "cluster.x-k8s.io/v1beta1, Kind=MachinePool"
Name: "pool1", Namespace: "default"
for: "cluster-02.yaml": error when patching "cluster-02.yaml": admission webhook "validation.machinepool.cluster.x-k8s.io" denied the request: MachinePool.cluster.x-k8s.io "pool1" is invalid: spec.clusterName: Forbidden: field is immutable

```

**Environment:**

- cluster-api-provider-azure version: 1.5.4
- Kubernetes version: (use `kubectl version`): 1.24.6
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by AAkindele** [comment]
Based on this issue <https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1689>, I believe a possible solution is to use the static pool0 and pool1 in AzureManagedMachinePool spec.name. Then include the cluster name in metadata.name for MachinePool and AzureManagedMachinePool. This would keep node pool names under the length requirements.

Example yaml:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cluster-01-pool0 # <- include cluster name
  namespace: default
spec:
  clusterName: cluster-01
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cluster-01
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: cluster-01-pool0 # <- include cluster name
      version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: cluster-01-pool0 # <- include cluster name
  namespace: default
spec:
  name: pool0 # <- add to template as static pool0 or pool1
  enableNodePublicIP: false
  mode: System
  osDiskSizeGB: 30
  sku: Standard_A2_v2
```
