### ISSUE TITLE
Make Image Parameters More User Friendly

### ISSUE THREAD

**Issue by juan-lee** [kubernetes-sigs/cluster-api-provider-azure#293]
/kind feature

**Describe the solution you'd like**
The various ways a user can specify an image is confusing due to the rules for knowing what parameters are required.

Consider using a claim like approach or using RuntimeExtension for the image field. That way, each of the image options can be expressed as a concrete type where it is obvious which fields are required.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/291/files#r332150770

**Comment by richardcase** [comment]
I look at this

**Comment by richardcase** [comment]
@juan-lee - looking at your comments [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/291/files), are you thinking that there will be 3 new resource kinds? 

For example, `AzureImageMarketplace`, `AzureImageSharedGallery`, `AzureImageWithID`. Something like this:

```go
type AzureImageMarketplace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec AzureImageMarketplaceSpec `json:"spec,omitempty"`
}

type AzureImageMarketplaceSpec struct {
	Publisher string `json:"publisher"`
	Offer     string `json:"offer"`
	SKU       string `json:"sku"`
	Version   string `json:"version"`
}
```
and then `Image`  in `VM` becomes something like:
```go
Image         corev1.ObjectReference `json:"image,omitempty"`
```
(or TypedLocalObjectReference if the same namespace is assumed)
There would then be validation of allowed types for `Image`. A bit like `DataSource` in `PersistentVolumeClaimSpec`

Another option would be to have an 'image source' interface and 3 structs with just the specific fields required, for example:

```go
type ImageMarketplace struct {
	Publisher string `json:"publisher"`
	Offer     string `json:"offer"`
	SKU       string `json:"sku"`
	Version   string `json:"version"`
}

type ImageSharedGallery struct {
	SubscriptionID string `json:"subscriptionID"`
	ResourceGroup  string `json:"resourceGroup"`
	Gallery        string `json:"gallery"`
	Name           string `json:"name"`
	Version        string `json:"version"`
}
```

**Comment by CecileRobertMichon** [comment]
related to #330

**Comment by CecileRobertMichon** [comment]
@richardcase thanks for taking a look at this!  Your proposal sounds good to me, I like the idea of using types for each way of specifying an image. Hopefully this will allow us to build stronger tests, documentation and input validation for user provided images.

**Comment by devigned** [comment]
+1 on the thx to @richardcase. 

I prefer the consistency and specificity of second approach where the Image will be treated like a PVC DataSource. The different types of image structs will provide strong typing with validation / documentation to help guide a user down a path of success.

**Comment by richardcase** [comment]
Thanks @CecileRobertMichon & @devigned 

I started on the different types / ObjectReference approach like PVC DataSource, so i'm glad you both thought that was the better way. Will get it complete asap.

**Comment by richardcase** [comment]
@devigned @CecileRobertMichon  - could i get your opinion on something? If we go down the different image structs/kind and use PVC DataSource pattern we'll end up with something like this:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AzureImageMarketplace
metadata:
  name: debian_buster
spec:
  publisher: "Debian"
  offer: "debian-10"
  sku: "10"
  version: "latest"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AzureMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-md-0
spec:
  template:
    spec:
      location: ${AZURE_LOCATION}
      vmSize: ${NODE_MACHINE_TYPE}
      osDisk:
        osType: "Linux"
        diskSizeGB: 30
        managedDisk:
          storageAccountType: "Premium_LRS"
      sshPublicKey: ${SSH_PUBLIC_KEY}
      image:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: AzureImageMarketplace
        name: debian_buster
```

Do you think this is ok? Or is this over complicating it?

If it is ok, then i have some thoughts on when we check that we have a valid image and the `status`  contents.
