### ISSUE TITLE
Agentpool is unable to update machinepool state in non-terminal state, resulting in cluster not being ready when running <clusterctl describe cluster> command

### ISSUE THREAD

**Issue by prajnutanix** [kubernetes-sigs/cluster-api-provider-azure#3009]
**What steps did you take and what happened:**
I created a CAPI cluster, using `clusterctl`, using a kind cluster for bootstrap and created a azure managed cluster with 2 machinepools. When I run `kubectl get cluster <cluster_name>`, I see that cluster is provisioned. I am able to dump the kubeconfig and run commands on the newly created cluster, so no issues with that. However, when I run `watch clusterctl describe cluster <cluster_name>` command, I see that the `READY` state for the `Machinepool` flips between `True` and `False`. When the Ready state is `False`, there are no error logs pertaining to it in the `capz-controller-manager` and `capi-controller-manager` pods. Describing the `Machinepool` object shows the following:

```
Status:
  Available Replicas:  2
  Bootstrap Ready:     true
  Conditions:
    Last Transition Time:  2023-01-04T01:19:31Z
    Message:               agentpools failed to create or update. err: failed to get desired parameters for resource cluster-sample/pool1 (service: agentpools): Unable to update existing agent pool in non terminal state. Agent pool must be in one of the following provisioning states: Canceled, Failed, or Succeeded. Actual state: Updating. Object will be requeued after 20s
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-01-03T22:25:00Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2023-01-04T01:19:31Z
    Message:               agentpools failed to create or update. err: failed to get desired parameters for resource cluster-sample/pool1 (service: agentpools): Unable to update existing agent pool in non terminal state. Agent pool must be in one of the following provisioning states: Canceled, Failed, or Succeeded. Actual state: Updating. Object will be requeued after 20s
    Reason:                Failed
    Severity:              Error
    Status:                False
    Type:                  InfrastructureReady
    Last Transition Time:  2023-01-03T22:25:00Z
    Status:                True
    Type:                  ReplicasReady
  Infrastructure Ready:    false
  Node Refs:
    Name:               aks-pool1-86783568-vmss000000
    UID:                a65af963-e4f7-47d5-b96d-c33d5572a8e9
    Name:               aks-pool1-86783568-vmss000001
    UID:                0e2077cb-1507-4ebe-aef4-b2113769b5ed
  Observed Generation:  2
  Phase:                Provisioned
  Ready Replicas:       2
  Replicas:             2
```

**What did you expect to happen:**
The clusterctl command should show the correct status. There is no issue with the newly created cluster, and it should report the status as `True` and must not flip values between `True` and `False` at random intervals.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 1.6.0
- minikube/kind version: v0.17.0
- Kubernetes version: (use `kubectl version`): v1.23.12
- OS (e.g. from `/etc/os-release`): "CentOS Linux 7 (Core)"

/kind bug
area/clusterctl , area/bootstrap

**Comment by CecileRobertMichon** [comment]
@nojnhuh PTAL

**Comment by nojnhuh** [comment]
Hi @prajnutanix, this looks like a situation where CAPZ is continuously updating the resources in AKS to match the desired state specified in the CAPI/CAPZ resources. That could happen if there's a bug in CAPZ, or it might be an issue where some other mechanism is also attempting to reconcile a different state than CAPZ. Does that sound like it might be the cause in this case?

I tried deploying our [default managed cluster template](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/6b5b078ffec909810a295747839891f88989c9df/templates/cluster-template-aks.yaml) using Kubernetes v1.23.12 with CAPZ v1.6.0 and I'm not seeing the behavior you describe. Could you please share the full YAML definitions of the MachinePool and AzureManagedMachinePool resources? And have any other changes been made to the node pools or the cluster with something external to CAPZ, like the `az` CLI or in the Azure portal?

**Comment by prajnutanix** [comment]
Hi @nojnhuh , thank you for taking a look at this. This is the yaml that I am trying to apply:

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: praj-capz-aks-cluster
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: praj-capz-aks-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: praj-capz-aks-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: praj-capz-aks-cluster
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: westus
  resourceGroupName: praj-capz-aks-cluster
  sshPublicKey: ""
  subscriptionID: ****
  version: v1.23.12
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: praj-capz-aks-cluster
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: pool0
  namespace: default
spec:
  clusterName: praj-capz-aks-cluster
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: praj-capz-aks-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pool0
      version: v1.23.12
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: pool0
  namespace: default
spec:
  enableNodePublicIP: false
  mode: System
  osDiskSizeGB: 30
  sku: Standard_D8s_v4
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: pool1
  namespace: default
spec:
  clusterName: praj-capz-aks-cluster
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: praj-capz-aks-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: pool1
      version: v1.23.12
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: pool1
  namespace: default
spec:
  enableNodePublicIP: false
  mode: User
  osDiskSizeGB: 40
  scaleSetPriority: Regular
  sku: Standard_D8s_v4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 229e7ad2-ff79-4013-86c0-45cf29358cd7
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: ****
  type: ServicePrincipal

```

I have redacted the tenantID and subscription from this yaml.  There are no other changes done after this file was created using the command:

```
clusterctl init --infrastructure azure -v 9
clusterctl generate cluster <cluster_name> --infrastructure azure --kubernetes-version "v1.23.12" --flavor aks > cluster.yaml
```
Once this cluster was provisioned (checked using `kubectl get cluster <cluster_name>` command, I put a watch on clusterctl describe cluster like I mentioned in the bug description. There were no changes done externally to nodepool or portal (other than creating a SP with contributor IAM), or using az cli

**Comment by nojnhuh** [comment]
Thanks @prajnutanix, unfortunately I still don't see that behavior when I deploy that cluster. I only changed the region from `westus` to `eastus` where my subscription has quota.

@CecileRobertMichon Do you know what more I could try to debug this? Or if there's a way to see exactly what the controller is continuously trying to update?

**Comment by CecileRobertMichon** [comment]
@nojnhuh have you tried this with the same version of CAPZ @prajnutanix is using (seems like v1.6.0?)? or controversy, @prajnutanix could you please try the latest release of CAPZ that got released today (v1.7.0)?

If you can still repro with v1.7.0, increasing the controller verbosity should tell you what the diff is (added in PR #2829)

**Comment by nojnhuh** [comment]
> @nojnhuh have you tried this with the same version of CAPZ @prajnutanix is using (seems like v1.6.0?)?

Yes, I was trying with CAPZ v1.6.0.

> If you can still repro with v1.7.0, increasing the controller verbosity should tell you what the diff is (added in PR #2829)

That PR adds logging diffs for changes to AzureManagedControlPlane, but it looks like in this case the updates are for an AzureManagedMachinePool which the controller doesn't log diffs for currently.

**Comment by CecileRobertMichon** [comment]
>  in this case the updates are for an AzureManagedMachinePool which the controller doesn't log diffs for currently.

aah you're correct, that's too bad :(  maybe an opportunity to add something similar for agentpools?

**Comment by prajnutanix** [comment]
I am able to repro this issue in CAPZ v1.7.0 version too. I just did a small 2.18 min screen recording.  Watch the flip happen just around 2min mark (between 1min 57sec - 2min 02sec). This loops around, and keeps flipping back and forth. 

https://user-images.githubusercontent.com/104871776/212790441-3bd2bd4a-bde8-4c26-a997-7b2a1f23847c.mov

**Comment by nojnhuh** [comment]
@prajnutanix I tried this again with v1.7.0 of CAPZ and still can't reproduce. My cluster seems stable over at least 20 minutes.
```
NAME                                                                 READY  SEVERITY  REASON  SINCE  MESSAGE 
Cluster/praj-capz-aks-cluster                                        True                     21m             
├─ClusterInfrastructure - AzureManagedCluster/praj-capz-aks-cluster                                           
├─ControlPlane - AzureManagedControlPlane/praj-capz-aks-cluster      True                     21m             
└─Workers                                                                                                     
  ├─MachinePool/pool0                                                True                     21m             
  └─MachinePool/pool1                                                True                     21m             
```

Have you seen a different instance of this same cluster definition flipping between ready/not ready? Or on a different CAPZ installation?

**Comment by prajnutanix** [comment]
@nojnhuh , yes, I have seen different clusters created with the **same** yaml spec, created on different subscriptions with workload clusters running on different machines every time which shows the same error. That said, this also happens when we add `virtualNetwork` block in `AzureManagedControlPlane` yaml spec, to deploy CAPI cluster on a same existing VNET. These are the 2 different variants of CAPZ installation that I have tried where this happens every time.

**Comment by nojnhuh** [comment]
Sorry, I still can't see the cluster flip between ready/not ready. I tried deploying the same cluster with the following added to the AzureManagedControlPlane and using CAPZ v1.7.0:
```yaml
  virtualNetwork:
    name: issue-3009
    resourceGroup: issue-3009
    cidrBlock: "10.0.0.0/16"
    subnet:
      name: default
      cidrBlock: "10.0.0.0/24"
```

@prajnutanix I'm not confident the capz-controller-manager logs on your cluster would point to the root cause even with the verbosity turned all the way up. I'll work on a change like #2829 for AzureManagedMachinePool and make sure that gets backported so it'll be included in a future (but hopefully the next) v1.7 patch release. Until we publish a release with that change, if you're willing to set up a dev environment and can reproduce this issue with that, then feel free to apply the same change and see if you can tell exactly what the controller is trying to update.
