### ISSUE TITLE
SpotVMOptions with AzureManagedMachinePool Supported?

### ISSUE THREAD

**Issue by lmcdasm** [kubernetes-sigs/cluster-api-provider-azure#3070]
/kind bug

**Describe the solution you'd like**
in the SPOT options, you can provide spotVMOptions for AzureMachinePool for the VMs, however when we use AzureManagedMachinePool there doesnt seem to be support for that option (or perhaps im looking in the wrong place)?  - marked it below with ## THIS IS ## 

error when kubectl apply the manifest 
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/9358276/213840123-46a8ac10-47a8-4d9b-b5ce-888924c80bae.png">

When creating an AKS (from say az cli or via the UI) you can use the Spot option for VMs backing the User Pools (not so for Control plane - for obvious reasons).  

Here is an example of a AKS User Pool that is backed by Spot instances  

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/9358276/213839964-2971290c-5827-460e-883d-d09dd0c8c762.png">

here is the Manifest that im using (generated pretty much from the tutorial/docs provided) 

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: azure-managed-gen-ad3941-clus
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: azure-managed-gen-ad3941-clus
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: azure-managed-gen-ad3941-clus
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: azure-managed-gen-ad3941-clus
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: eastus2
  resourceGroupName: azure-managed-gen-ad3941-clus
  sshPublicKey: ""
  subscriptionID: 4cebd231-affb-455b-9e26-dfd18bb64df3
  version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: azure-managed-gen-ad3941-clus
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: azure-managed-gen-ad3941-clus-pool0
  namespace: default
spec:
  clusterName: azure-managed-gen-ad3941-clus
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: azure-managed-gen-ad3941-clus
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: azure-managed-gen-ad3941-clus-pool0
      version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: azure-managed-gen-ad3941-clus-pool0
  namespace: default
spec:
  mode: System
  name: pool0
  sku: Standard_B2s
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: azure-managed-gen-ad3941-clus-pool1
  namespace: default
spec:
  clusterName: azure-managed-gen-ad3941-clus
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: azure-managed-gen-ad3941-clus
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: azure-managed-gen-ad3941-clus-pool1
      version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: azure-managed-gen-ad3941-clus-pool1
  namespace: default
spec:
  mode: User
  name: pool1
  sku: Standard_D2as_v5
  ## THIS IS WHAT I WANT TO DO ESSENTIALLY##
  spotVMOptions: {}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: xxxxx
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: xxxxxx
  type: ServicePrincipal
```

**Environment:**

- cluster-api-provider-azure version: GitVersion:"v1.3.2",
- Kubernetes version: (use `kubectl version`): , GitVersion:"v1.25.3"
- OS (e.g. from `/etc/os-release`): "22.04.1 LTS JAMMY"
