### ISSUE TITLE
subnetname validation webhook wrong

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#3202]
/kind bug

**What steps did you take and what happened:**
upgraded to 1.7.2
```
one or more objects failed to apply, reason: admission webhook "validation.azuremachinepool.infrastructure.cluster.x-k8s.io" denied the request: cannot set both NetworkInterfaces and machine SubnetName. Retrying attempt #2 at 2:07PM.
```

example yaml we have (since we used to be on a previous version without networkInterfaces):
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: REDACTED
  namespace: REDACTED
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  location: westeurope
  template:
    subnetName: REDACTED
[...]
```

**What did you expect to happen:**
subnetName is deprecated but it should still work and not break with minor releases.

**Comment by mweibel** [comment]
ah, the issue is: the mutating webhook edits the AzureMachinePool and replaces the subnetName with a networkInterfaces property:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: REDACTED
  namespace: REDACTED
spec:
  # [...]
  template:
    # [...]
    networkInterfaces:
    - privateIPConfigs: 1
      subnetName: gpu-spot-subnet
```

our GitOps tool of choice (ArgoCD) then tries to reconcile it again by setting the subnetName which then generates an error.
