### ISSUE TITLE
SSH public key does not work in windows nodes

### ISSUE THREAD

**Issue by mweibel** [kubernetes-sigs/cluster-api-provider-azure#3232]
/kind bug

**What steps did you take and what happened:**
SSH public keys are not supported for Windows instances (Machines or MachinePoolMachines does not matter). Setting a `sshPublicKey` does not actually do something for windows nodes.

Workaround: specify the SSH public key in `KubeadmConfig.spec.users`:
```yaml
  users:
    - groups: Administrators
      name: REDACTED
      sshAuthorizedKeys:
        - "ssh-rsa REDACTED"
```

However we can't use `capi` as the name. Previous versions of cloudbase-init permitted to specify `capi` as the username so at least you wouldn't need another user. Latest tests showed that the provisioning fails because of a username conflict so you ought to use another name than the default `capi`. But at least it works this way.

Example AzureMachinePool spec for specifying the SSH public key:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: REDACTED
  namespace: REDACTED
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  location: westeurope
  template:
    networkInterfaces:
    - subnetName: REDACTED-subnet
    image:
      sharedGallery:
        REDACTED
    osDisk:
      cachingType: ReadOnly
      diskSizeGB: 750
      osType: Windows
      diffDiskSettings:
        option: Local # ephemeral OS disk
    sshPublicKey: REDACTED_SSH_PUBLIC_KEY
    vmSize: Standard_D96as_v4
    spotVMOptions: {}
  identity: None
```

Relevant code which show windows is ignoring SSHPublicKey:
- [Code for Machines](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/virtualmachines/spec.go#L250-L275)
- [Code for MachinePools](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/services/scalesets/scalesets.go#L856-L881)

**What did you expect to happen:**
SSHPublicKey works as advertised and sets up an SSH authorized key. 

**Anything else you would like to add:**
IIRC when setting an SSH public key one needs to do the following steps:
```
C:\Users\{USERNAME}\.ssh\authorized_keys` as well as `C:\ProgramData\ssh\administrators_authorized_keys` need to have the public key and with the right permissions:

icacls.exe "C:\ProgramData\ssh\administrators_authorized_keys" /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"
icacls.exe "C:\Users\{USERNAME}\.ssh\authorized_keys" /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"
```
Unless I'm missing something (which may well be, not a windows expert) it's unfortunately not just a simple step of putting the file in the right location. 

**Environment:**

- cluster-api-provider-azure version: current main
- Kubernetes version: (use `kubectl version`): 1.24.11
- OS (e.g. from `/etc/os-release`): windows 2019
