### ISSUE TITLE
Unable to install AKS, cant set feature flag

### ISSUE THREAD

**Issue by Boes-man** [kubernetes-sigs/cluster-api-provider-azure#3240]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Followed the [AKS guide](https://capz.sigs.k8s.io/topics/managedcluster.html) but kubectl apply -f cluster.yaml fails with the below message and the docs dont describe how to enable the feature flag.
```k apply -f cluster.yaml
cluster.cluster.x-k8s.io/test-dw-aks unchanged
azuremanagedcluster.infrastructure.cluster.x-k8s.io/test-dw-aks unchanged
machinepool.cluster.x-k8s.io/test-dw-aks-pool0 unchanged
azuremanagedmachinepool.infrastructure.cluster.x-k8s.io/test-dw-aks-pool0 unchanged
machinepool.cluster.x-k8s.io/test-dw-aks-pool1 unchanged
azuremanagedmachinepool.infrastructure.cluster.x-k8s.io/test-dw-aks-pool1 unchanged
azureclusteridentity.infrastructure.cluster.x-k8s.io/cluster-identity unchanged
Error from server (spec: Forbidden: can be set only if the AKS feature flag is enabled): error when creating "cluster.yaml": admission webhook "validation.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io" denied the request: spec: Forbidden: can be set only if the AKS feature flag is enabled
```
```
 cat cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-dw-aks
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: test-dw-aks
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: test-dw-aks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: test-dw-aks
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: westus2
  resourceGroupName: test-dw-aks
  sshPublicKey: ""
  subscriptionID: 793..
  version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: test-dw-aks
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: test-dw-aks-pool0
  namespace: default
spec:
  clusterName: test-dw-aks
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test-dw-aks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: test-dw-aks-pool0
      version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: test-dw-aks-pool0
  namespace: default
spec:
  mode: System
  name: pool0
  sku: Standard_D2s_v3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: test-dw-aks-pool1
  namespace: default
spec:
  clusterName: test-dw-aks
  replicas: 2
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test-dw-aks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: test-dw-aks-pool1
      version: v1.24.6
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: test-dw-aks-pool1
  namespace: default
spec:
  mode: User
  name: pool1
  sku: Standard_D2s_v3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: 723fe..
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: 9e..
  type: ServicePrincipal
```

```
extract from deployment.apps/capi-controller-manager
    Args:
      --leader-elect
      --metrics-bind-addr=localhost:8080
      --feature-gates=AKS=true,MachinePool=true,ClusterResourceSet=true,ClusterTopology=true,RuntimeSDK=true
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:healthz/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
```

```env
AZURE_LOCATION=westus2
AZURE_CONTROL_PLANE_MACHINE_TYPE=Standard_D2s_v3
AZURE_NODE_MACHINE_TYPE=Standard_D2s_v3
CLUSTER_NAME=test-dw-aks
WORKER_MACHINE_COUNT=2
KUBERNETES_VERSION=v1.24.6
AZURE_RESOURCE_GROUP=test-dw-aks
AZURE_SUBSCRIPTION_ID=79...
AZURE_CLIENT_SECRET=C8....
AZURE_CLIENT_ID=723...
AZURE_CLUSTER_IDENTITY_SECRET_NAME=cluster-identity-secret
AZURE_CLUSTER_IDENTITY_SECRET_NAMESPACE=default
CLUSTER_IDENTITY_NAME=cluster-identity
EXP_MACHINE_POOL=true
EXP_AKS=true
AZURE_TENANT_ID=9e6a....
EXP_AKS_RESOURCE_HEALTH=true
```

Initially the MachinePool feature flag was also required, but i could add via `kubectl edit -n capi-system deployment.apps/capi-controller-manager`. Cant find a description on how to add AKS in there.
So looks like feature flag VARS aren't working at least for me.

**What did you expect to happen:**
AKS cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: clusterctl version available: v1.3.3
- Kubernetes version: (use `kubectl version`): 
`WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-25T14:32:03Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}`
- OS (e.g. from `/etc/os-release`): macos m1
