### ISSUE TITLE
MachinePool version is optional but implicitly required by AzureManagedMachinePool

### ISSUE THREAD

**Issue by mjnovice** [kubernetes-sigs/cluster-api-provider-azure#3435]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Provision an AKS managed cluster, with the following example manifest

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: sfd-${NAME}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${NAME}
  namespace: sfd-${NAME}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${NAME}
    namespace: sfd-${NAME}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${NAME}
    namespace: sfd-${NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${NAME}
  name: ${NAME}
  namespace: sfd-${NAME}
spec:
  subscriptionID: 64fdac10-935b-40e6-bf28-f7dc093f7f76
  additionalTags:
    Owner: mayank.jha@uipath.com
    Project: Service Fabric
  apiServerAccessProfile:
    enablePrivateCluster: true
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${NAME}
  loadBalancerSKU: Standard
  location: westeurope
  networkPlugin: azure
  resourceGroupName: ${NAME}
  version: v1.23.12
  virtualNetwork:
    cidrBlock: 10.0.0.0/8
    name: ${NAME}
    resourceGroup: ${NAME}
    subnet:
      cidrBlock: 10.240.0.0/16
      name: ${NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: ${NAME}-0
  namespace: sfd-${NAME}
spec:
  enableNodePublicIP: false
  maxPods: 100
  mode: System
  name: pool0
  nodeLabels:
    dummykey: dummyval
  osDiskSizeGB: 512
  osDiskType: Managed
  osType: Linux
  scaling:
    maxSize: 8
    minSize: 3
  sku: Standard_D8s_v3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${NAME}-0
  namespace: sfd-${NAME}
spec:
  clusterName: ${NAME}
  replicas: 3
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: ${NAME}-0
        namespace: sfd-${NAME}
      version: v1.23.12
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${NAME}
  namespace: sfd-${NAME}
spec:
  allowedNamespaces:
    list:
    - sfd-${NAME}
  clientID: 0ddc4f44-26cc-4018-9336-83e375627d99
  clientSecret:
    name: azcapi-infrasfea
    namespace: as-air-cluster-system
  tenantID: d8353d2a-b153-4d17-8827-902c51f72357
  type: ServicePrincipal
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${NAME}
  namespace: sfd-${NAME}
```

The machinePool seems to be in a loop of `update` even when the spec doesn't change at all. 

```
 conditions:
  - lastTransitionTime: "2023-04-17T00:43:31Z"
    message: 'agentpools failed to create or update. err: failed to get desired parameters
      for resource devmj-mj-test5/pool0 (service: agentpools): Unable to update existing
      agent pool in non terminal state. Agent pool must be in one of the following
      provisioning states: Canceled, Failed, or Succeeded. Actual state: Updating.
      Object will be requeued after 20s'
    reason: Failed
    severity: Error
    status: "False"
    type: Ready
```

<img width="915" alt="image" src="https://user-images.githubusercontent.com/3083824/232353918-572e5d21-58f8-45f4-b15c-ac72de038cc2.png">

On the Azure portal, there seems to be redundant set of updates.

**What did you expect to happen:**

There shouldn't be update calls when there is no apparent update to the `MachinePool`

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: `1.8.2`
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-11-02T03:24:50Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}`
- OS (e.g. from `/etc/os-release`): macOS 13.3.1 (22E261)
