### ISSUE TITLE
With the support for configurable network interfaces, user should be able to create multiple subnets for a control-plane node

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#3506]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- While testing Azure CNI v1 with the below `AzureCluster` template, the resource `AzureCluster` does not get created with the error `The AzureCluster "azure-cni-v1-25064" is invalid: spec.networkSpec.subnets[3]: Duplicate value: map[string]interface {}{"name":"cp-subnet-1"}`
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${CLUSTER_IDENTITY_NAME}
  location: ${AZURE_LOCATION}
  networkSpec:
    subnets:
    - name: node-subnet-1
      role: node
    - name: node-subnet-2
      role: node
    - name: cp-subnet-1
      role: control-plane
    - name: cp-subnet-2
      role: control-plane
    vnet:
      name: ${AZURE_VNET_NAME:=${CLUSTER_NAME}-vnet}
  resourceGroup: ${AZURE_RESOURCE_GROUP:=${CLUSTER_NAME}}
  subscriptionID: ${AZURE_SUBSCRIPTION_ID}
```
- This happens because of two reasons
  - Primarily : [At https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/de72779812a86c2cda550f07cfbbc31e76547432/api/v1alpha3/types.go#L459](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/de72779812a86c2cda550f07cfbbc31e76547432/api/v1alpha3/types.go#L459-L466) , we assume that there would only be one control-plane subnet. 
  - Secondly: While setting [defaults](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/de72779812a86c2cda550f07cfbbc31e76547432/api/v1beta1/azurecluster_default.go#L86-L104), we _update_ [all the `role: control-plane` subnets](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/de72779812a86c2cda550f07cfbbc31e76547432/api/v1alpha4/types.go#L531C1-L537) with the one we found above. 
- This results in the error we see while creating AzureCluster resource with multiple subnets of type `role: control-plane`

**What did you expect to happen:**
- User should be able to create multiple subnets with of the type `role: control-plane` for control-plane nodes.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: `v1.8.3`
- Kubernetes version: (use `kubectl version`): `v1.25.9` 
- OS (e.g. from `/etc/os-release`):
