### ISSUE TITLE
Upgrade CAPZ from v1.6.3 to v.9.1 fails at the AzureClusterTemplate is immutable

### ISSUE THREAD

**Issue by xiujuanx** [kubernetes-sigs/cluster-api-provider-azure#3564]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When I try to upgrade CAPZ from v1.6.3 to v1.9.1, it fails and reports the below error:
```
14:12:09      API server says: admission webhook "validation.azureclustertemplate.infrastructure.cluster.x-k8s.io" denied the request:
14:12:09        AzureClusterTemplate.infrastructure.cluster.x-k8s.io "tkg-azure-default-v1.0.0-cluster" is invalid: [AzureClusterTemplate.spec.template.spec: Invalid value: v1beta1.AzureClusterTemplate{TypeMeta:v1.TypeMeta{Kind:"AzureClusterTemplate", APIVersion:"infrastructure.cluster.x-k8s.io/v1beta1"}, ObjectMeta:v1.ObjectMeta{Name:"tkg-azure-default-v1.0.0-cluster", GenerateName:"", Namespace:"tkg-system", SelfLink:"", UID:"7e711cb7-3528-48a0-93c0-8ee51e8a4c85", ResourceVersion:"10435", Generation:2, CreationTimestamp:time.Date(2023, time.May, 14, 5, 55, 35, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"kapp.k14s.io/app":"1684043733006179129", "kapp.k14s.io/association":"v1.315b59ca9e760d3a47aa0129cd87c646"}, Annotations:map[string]string{"kapp.k14s.io/identity":"v1;tkg-system/infrastructure.cluster.x-k8s.io/AzureClusterTemplate/tkg-azure-default-v1.0.0-cluster;infrastructure.cluster.x-k8s.io/v1beta1"}, OwnerReferences:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"cluster.x-k8s.io/v1beta1", Kind:"ClusterClass", Name:"tkg-azure-default-v1.0.0", UID:"8178c37c-6387-4ac9-a8f0-1188281aee0d", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}, Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"manager", Operation:"Update", APIVersion:"infrastructure.cluster.x-k8s.io/v1beta1", Time:time.Date(2023, time.May, 14, 5, 44, 28, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000a6ac78), Subresource:""}, v1.ManagedFieldsEntry{Manager:"kapp", Operation:"Update", APIVersion:"infrastructure.cluster.x-k8s.io/v1beta1", Time:time.Date(2023, time.May, 14, 6, 5, 43, 0, time.Local), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000a6aca8), Subresource:""}}}, Spec:v1beta1.AzureClusterTemplateSpec{Template:v1beta1.AzureClusterTemplateResource{Spec:v1beta1.AzureClusterTemplateResourceSpec{AzureClusterClassSpec:v1beta1.AzureClusterClassSpec{SubscriptionID:"****", Location:"westus2", ExtendedLocation:(*v1beta1.ExtendedLocationSpec)(nil), AdditionalTags:v1beta1.Tags(nil), IdentityRef:(*v1.ObjectReference)(nil), AzureEnvironment:"AzurePublicCloud", CloudProviderConfigOverrides:(*v1beta1.CloudProviderConfigOverrides)(nil)}, NetworkSpec:v1beta1.NetworkTemplateSpec{NetworkClassSpec:v1beta1.NetworkClassSpec{PrivateDNSZoneName:""}, Vnet:v1beta1.VnetTemplateSpec{VnetClassSpec:v1beta1.VnetClassSpec{CIDRBlocks:[]string{"10.0.0.0/8"}, Tags:v1beta1.Tags(nil)}, Peerings:v1beta1.VnetPeeringsTemplateSpec(nil)}, Subnets:v1beta1.SubnetTemplatesSpec{v1beta1.SubnetTemplateSpec{SubnetClassSpec:v1beta1.SubnetClassSpec{Name:"management-cluster-controlplane-subnet", Role:"control-plane", CIDRBlocks:[]string{"10.0.0.0/16"}, ServiceEndpoints:v1beta1.ServiceEndpoints(nil), PrivateEndpoints:v1beta1.PrivateEndpoints(nil)}, SecurityGroup:v1beta1.SecurityGroupClass{SecurityRules:v1beta1.SecurityRules(nil), Tags:v1beta1.Tags(nil)}, NatGateway:v1beta1.NatGatewayClassSpec{Name:""}}, v1beta1.SubnetTemplateSpec{SubnetClassSpec:v1beta1.SubnetClassSpec{Name:"management-cluster-node-subnet", Role:"node", CIDRBlocks:[]string{"10.1.0.0/16"}, ServiceEndpoints:v1beta1.ServiceEndpoints(nil), PrivateEndpoints:v1beta1.PrivateEndpoints(nil)}, SecurityGroup:v1beta1.SecurityGroupClass{SecurityRules:v1beta1.SecurityRules(nil), Tags:v1beta1.Tags(nil)}, NatGateway:v1beta1.NatGatewayClassSpec{Name:""}}}, APIServerLB:v1beta1.LoadBalancerClassSpec{SKU:"Standard", Type:"Public", IdleTimeoutInMinutes:(*int32)(0xc003f7ed58)}, NodeOutboundLB:(*v1beta1.LoadBalancerClassSpec)(nil), ControlPlaneOutboundLB:(*v1beta1.LoadBalancerClassSpec)(nil)}, BastionSpec:v1beta1.BastionTemplateSpec{AzureBastion:(*v1beta1.AzureBastionTemplateSpec)(nil)}}}}}: AzureClusterTemplate spec.template.spec field is immutable. Please create new resource instead. ref doc: https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/change-clusterclass.html
```
Compare the old AzureClusterTemplate with the new one, the only difference is the `spec.template.spec.networkSpec.nodeOutboundLB` field. The old one has some value, and the new one is nil.

**What did you expect to happen:**
Upgrade succeed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jackfrancis** [comment]
I initially suspected this change:


- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3365/files#diff-016ca697ac4323c794d5dda09a16fd6152518acb4e3da6efef765fe5011a796bR222

Thinking that we need to make the same webhook tolerance for `NodeOutboundLB` as we do for `AcceleratedNetworking` here:

- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3519

But in fact we are only entering into the updated code if the `NodeOutboundLB` is nil, which it is not in @xiujuanx's upgrade scenario.

@xiujuanx can you provide the AzureClusterTemplate configuration you're using on your v1.6.3 cluster and we can attempt to reproduce this upgrade bug?

cc @CecileRobertMichon in case she has more thoughts

**Comment by xiujuanx** [comment]
Thanks @jackfrancis , I think this is not an valid case. For our side, we are trying to modify the template spec. This violates the origin design of template concept. But anyway, I will put my scenario here in case your side has more concerns.
Before upgrade, our side is defining a AzureClusterTemplate is like the below one:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: #@ "tkg-azure-default-{}-cluster".format(data.values.AZURE_CLUSTER_CLASS_VERSION)
  namespace: #@ data.values.NAMESPACE
spec:
  template:
    spec:
      azureEnvironment: #@ data.values.AZURE_ENVIRONMENT
      location: #@ data.values.AZURE_LOCATION
      networkSpec:
        vnet:
          cidrBlock: #@ data.values.AZURE_VNET_CIDR
        subnets:
        #@ if data.values.AZURE_CONTROL_PLANE_SUBNET_NAME == "":
        - name: management-cluster-controlplane-subnet
          role: control-plane
          cidrBlock: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR
        #@ else:
        - name: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_NAME
          role: control-plane
          cidrBlock: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR
        #@ end
        #@ if data.values.AZURE_NODE_SUBNET_NAME == "":
        - name: management-cluster-node-subnet
          role: node
          cidrBlock: #@ data.values.AZURE_NODE_SUBNET_CIDR
        #@ else:
        - name: #@ data.values.AZURE_NODE_SUBNET_NAME
          role: node
          cidrBlock: #@ data.values.AZURE_NODE_SUBNET_CIDR
        #@ end
      subscriptionID: #@ data.values.AZURE_SUBSCRIPTION_ID
```
But as we all known, the `cidrBlock` is deprecated since the v1beta1. So we change the template to be:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: #@ "tkg-azure-default-{}-cluster".format(data.values.AZURE_CLUSTER_CLASS_VERSION)
  namespace: #@ data.values.NAMESPACE
spec:
  template:
    spec:
      azureEnvironment: #@ data.values.AZURE_ENVIRONMENT
      location: #@ data.values.AZURE_LOCATION
      networkSpec:
        vnet:
          #@ if data.values.AZURE_VNET_CIDR != "":
          cidrBlocks: #@ data.values.AZURE_VNET_CIDR.split(",")
          #@ end
        subnets:
        #@ if data.values.AZURE_CONTROL_PLANE_SUBNET_NAME == "":
        - name: management-cluster-controlplane-subnet
          role: control-plane
          #@ if data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR != "":
          cidrBlocks: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR.split(",")
          #@ end
        #@ else:
        - name: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_NAME
          role: control-plane
          #@ if data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR != "":
          cidrBlocks: #@ data.values.AZURE_CONTROL_PLANE_SUBNET_CIDR.split(",")
          #@ end
        #@ end
        #@ if data.values.AZURE_NODE_SUBNET_NAME == "":
        - name: management-cluster-node-subnet
          role: node
          #@ if data.values.AZURE_NODE_SUBNET_CIDR != "":
          cidrBlocks: #@ data.values.AZURE_NODE_SUBNET_CIDR.split(",")
          #@ end
        #@ else:
        - name: #@ data.values.AZURE_NODE_SUBNET_NAME
          role: node
          #@ if data.values.AZURE_NODE_SUBNET_CIDR != "":
          cidrBlocks: #@ data.values.AZURE_NODE_SUBNET_CIDR.split(",")
          #@ end
        #@ end
      subscriptionID: #@ data.values.AZURE_SUBSCRIPTION_ID
```
Then upgrade, this issue happens.
