### ISSUE TITLE
Cluster bootstrap stuck at first controller - Scaling up control plane failing

### ISSUE THREAD

**Issue by log1cb0mb** [kubernetes-sigs/cluster-api-provider-azure#3701]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Cluster bootstrap failing with process stuck at bootstrapping first controller node only.  `capi-kubeadm-control-plane-controller-manager` stuck looping through:

```
capi-kubeadm-control-plane-system capi-kubeadm-control-plane-controller-manager-7f4c744f4d-sxlp6 manager I0711 10:55:31.060727       1 controller.go:404] "Scaling up control plane" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="pck/pck-control-plane" namespace="pck" name="pck-control-plane" reconcileID=09f8c268-4594-4bb1-9f60-8c2e02dcfd84 Cluster="pck/pck" Desired=3 Existing=1
capi-kubeadm-control-plane-system capi-kubeadm-control-plane-controller-manager-7f4c744f4d-sxlp6 manager I0711 10:55:31.061890       1 scale.go:213] "Waiting for control plane to pass preflight checks" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="pck/pck-control-plane" namespace="pck" name="pck-control-plane" reconcileID=09f8c268-4594-4bb1-9f60-8c2e02dcfd84 Cluster="pck/pck" failures="[machine pck-control-plane-hwdw2 does not have APIServerPodHealthy condition, machine pck-control-plane-hwdw2 does not have ControllerManagerPodHealthy condition, machine pck-control-plane-hwdw2 does not have SchedulerPodHealthy condition, machine pck-control-plane-hwdw2 does not have EtcdPodHealthy condition, machine pck-control-plane-hwdw2 does not have EtcdMemberHealthy condition]"
```

It is complaining about the first controller that is bootstrapped however kube API is reachable from management cluster, all aforementioned pods are also healthy so not sure what sort of health check is exactly failing.

```
k get azuremachines.infrastructure.cluster.x-k8s.io -A
NAMESPACE   NAME                      READY   REASON   STATE       AGE
pck         pck-control-plane-mpjp8   True             Succeeded   21h
```

```
k get azureclusters.infrastructure.cluster.x-k8s.io -A
NAMESPACE   NAME   CLUSTER   READY   REASON   AGE
pck         pck    pck       True             21h
```

```
clusterctl describe cluster pck -n pck
NAME                                                    READY  SEVERITY  REASON     SINCE  MESSAGE
Cluster/pck                                             False  Warning   ScalingUp  2m36s  Scaling up control plane to 3 replicas (actual 1)
├─ClusterInfrastructure - AzureCluster/pck              True                        2m36s
└─ControlPlane - KubeadmControlPlane/pck-control-plane  False  Warning   ScalingUp  21h    Scaling up control plane to 3 replicas (actual 1)
  └─Machine/pck-control-plane-hwdw2                     True                        21h
```

the behavior is same for internal/private cluster and even public cluster. The configurations currently being tried:

<details>
  <summary>Cluster Configuration</summary>

  ```
  apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  metadata:
    name: pck
    namespace: pck
  spec:
    clusterNetwork:
      pods:
        cidrBlocks:
        - 192.168.0.0/16
    controlPlaneRef:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlane
      name: pck-control-plane
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureCluster
      name: pck
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: AzureCluster
  metadata:
    name: pck
    namespace: pck
  spec:
    identityRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureClusterIdentity
      name: cluster-identity
      namespace: capi-mgmt
    location: westeurope
    networkSpec:
      apiServerLB:
        type: Internal
        frontendIPs:
          - name: lb-private-ip-frontend
            privateIP: 172.16.100.20
      controlPlaneOutboundLB:
        frontendIPsCount: 1
      nodeOutboundLB:
        frontendIPsCount: 1
      vnet:
        name: pck
        cidrBlocks:
          - 172.16.100.0/24
        peerings:
        - resourceGroup: management-cluster
          remoteVnetName: management-cluster
      subnets:
      - name: control-plane-subnet
        role: control-plane
        cidrBlocks:
        - 172.16.100.0/27
      - name: node-subnet
        role: node
        cidrBlocks:
        - 172.16.100.32/27
    resourceGroup: pck
    subscriptionID: xxxxxxxxxxxxxxxxxxxxxx
  ---
  apiVersion: controlplane.cluster.x-k8s.io/v1beta1
  kind: KubeadmControlPlane
  metadata:
    name: pck-control-plane
    namespace: pck
  spec:
    kubeadmConfigSpec:
      clusterConfiguration:
        apiServer:
          extraArgs:
            cloud-provider: external
          timeoutForControlPlane: 20m
        controllerManager:
          extraArgs:
            allocate-node-cidrs: "false"
            cloud-provider: external
            cluster-name: pck
        etcd:
          local:
            dataDir: /var/lib/etcddisk/etcd
            extraArgs:
              quota-backend-bytes: "8589934592"
      diskSetup:
        filesystems:
        - device: /dev/disk/azure/scsi1/lun0
          extraOpts:
          - -E
          - lazy_itable_init=1,lazy_journal_init=1
          filesystem: ext4
          label: etcd_disk
        - device: ephemeral0.1
          filesystem: ext4
          label: ephemeral0
          replaceFS: ntfs
        partitions:
        - device: /dev/disk/azure/scsi1/lun0
          layout: true
          overwrite: false
          tableType: gpt
      files:
      - contentFrom:
          secret:
            key: control-plane-azure.json
            name: pck-control-plane-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
      initConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            azure-container-registry-config: /etc/kubernetes/azure.json
            cloud-provider: external
          name: '{{ ds.meta_data["local_hostname"] }}'
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            azure-container-registry-config: /etc/kubernetes/azure.json
            cloud-provider: external
          name: '{{ ds.meta_data["local_hostname"] }}'
      mounts:
      - - LABEL=etcd_disk
        - /var/lib/etcddisk
      postKubeadmCommands:
      - if [ -f /tmp/kubeadm-join-config.yaml ] || [ -f /run/kubeadm/kubeadm-join-config.yaml ]; then echo '127.0.0.1   apiserver.pck.capz.io apiserver' >> /etc/hosts; fi
      preKubeadmCommands:
      - if [ -f /tmp/kubeadm.yaml ] || [ -f /run/kubeadm/kubeadm.yaml ]; then echo '127.0.0.1   apiserver.pck.capz.io apiserver' >> /etc/hosts; fi
    machineTemplate:
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate
        name: pck-control-plane
    replicas: 3
    version: 1.26.5
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: AzureMachineTemplate
  metadata:
    name: pck-control-plane
    namespace: pck
  spec:
    template:
      spec:
        dataDisks:
        - diskSizeGB: 256
          lun: 0
          nameSuffix: etcddisk
        osDisk:
          diskSizeGB: 128
          osType: Linux
        sshPublicKey: c3NoLXJzYSxxxxxxx
        vmSize: Standard_D2s_v3
  ---
  apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
  kind: AzureClusterIdentity
  metadata:
    name: cluster-identity
    namespace: capi-mgmt
  spec:
    type: UserAssignedMSI
    tenantID: "xxxx"
    clientID: "xxxx"
    resourceID: "xxx"
    allowedNamespaces: {}
  ```
</details>

**What did you expect to happen:**
First controller health checks to be passed and process moving to scaling/bringing up remaining controller nodes of the 3 node cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.9.4
- Kubernetes version: (use `kubectl version`): 1.26.5
- OS (e.g. from `/etc/os-release`): Ubuntu-22_04
