### ISSUE TITLE
"Default" VM image logic does not work

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-azure#384]
/kind bug

**What steps did you take and what happened:**
Declare a `AzureMachine` without an image defined. For example:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachine
metadata:
  name: capi-azure-management-controlplane-0
  namespace: mgmt-clusters
spec:
  location: centralus
  osDisk:
    diskSizeGB: 30
    managedDisk:
      storageAccountType: Standard_LRS
    osType: Linux
  sshPublicKey: ABCDF...
  vmSize: Standard_DS2_v2
```

**What did you expect to happen:**
This should use a default image when provisioning the VM.

However, there is an error when trying to use the default image:
```bash
E0209 09:56:12.968748   76135 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create AzureMachine VM: failed to create vm capi-azure-management-controlplane-0 : failed to create or get machine: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code=\"PlatformImageNotFound\" Message=\"The platform image 'cncf-upstream:capi:k8s-1dot16dot1-ubuntu-1804:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile\" Target=\"imageReference\""  "controller"="azuremachine" "request"={"Namespace":"mgmt-clusters","Name":"capi-azure-management-controlplane-0"}
```

We are trying to use a version set to `latest`:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/cloud/defaults.go#L154

But this `latest` version doesn't exist:

![image](https://user-images.githubusercontent.com/198425/74100155-b02e8a00-4b23-11ea-806f-56eb7b836f17.png)

**Anything else you would like to add:**
We should use `VirtualMachineImagesClient` and `List` to get a list of images and pick the latest version.
