### ISSUE TITLE
Audit the images published for different OS and K8s versions 

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#3885]
/kind cleanup

**What needs cleanup:**
[A clear and concise description of what needs to be cleaned up.]
- We should audit CAPZ reference images being published for different OS and K8s releases. 
- As of writing this issue, we are planning to publish 19 images in total for the following version matrix.
```yaml
  # Ubuntu 22.04
  - OS: "Ubuntu"
    OS_VERSION: "22.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.28.1"
  - OS: "Ubuntu"
    OS_VERSION: "22.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.27.5"
  - OS: "Ubuntu"
    OS_VERSION: "22.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.26.8"
  - OS: "Ubuntu"
    OS_VERSION: "22.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.25.13"

  # Ubuntu 20.04
  - OS: "Ubuntu"
    OS_VERSION: "20.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.28.1"
  - OS: "Ubuntu"
    OS_VERSION: "20.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.27.5"
  - OS: "Ubuntu"
    OS_VERSION: "20.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.26.8"
  - OS: "Ubuntu"
    OS_VERSION: "20.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.25.13"
  - OS: "Ubuntu"
    OS_VERSION: "20.04"
    OFFER: "capi"
    KUBERNETES_BOOTSTRAP_VERSION: ""
    KUBERNETES_VERSION: "1.24.17"

  # Windows 2019
  - OS: "Windows"
    OS_VERSION: "2019-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.28.0"
    KUBERNETES_VERSION: "1.28.1"
  - OS: "Windows"
    OS_VERSION: "2019-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.27.4"
    KUBERNETES_VERSION: "1.27.5"
  - OS: "Windows"
    OS_VERSION: "2019-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.26.7"
    KUBERNETES_VERSION: "1.26.8"
  - OS: "Windows"
    OS_VERSION: "2019-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.25.12"
    KUBERNETES_VERSION: "1.25.13"
  - OS: "Windows"
    OS_VERSION: "2019-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.24.16"
    KUBERNETES_VERSION: "1.24.17"

  # Windows 2022
  - OS: "Windows"
    OS_VERSION: "2022-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.28.0"
    KUBERNETES_VERSION: "1.28.1"
  - OS: "Windows"
    OS_VERSION: "2022-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.27.4"
    KUBERNETES_VERSION: "1.27.5"
 - OS: "Windows"
    OS_VERSION: "2022-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.26.7"
    KUBERNETES_VERSION: "1.26.8"
  - OS: "Windows"
    OS_VERSION: "2022-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.25.12"
    KUBERNETES_VERSION: "1.25.13"
  - OS: "Windows"
    OS_VERSION: "2022-containerd"
    OFFER: "capi-windows"
    KUBERNETES_BOOTSTRAP_VERSION: "1.24.16"
    KUBERNETES_VERSION: "1.24.17"

```

**Describe the solution you'd like**
[Description of how you would like the cleanup to be done.]
- Audit and potentially minimize the number of CAPZ reference images being published.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
