### ISSUE TITLE
AzureManagedMachinePool with Spot instances endlessly reconciles node taints

### ISSUE THREAD

**Issue by nojnhuh** [kubernetes-sigs/cluster-api-provider-azure#3976]
/kind bug
/area managedclusters

**What steps did you take and what happened:**
Create an AzureMachinePool that looks like this, using Spot instances and with no taints defined:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: jon-aks-$NAME
  namespace: default
spec:
  clusterName: jon-aks
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: jon-aks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: jon-aks-$NAME
      version: v1.26.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: jon-aks-$NAME
  namespace: default
spec:
  mode: User
  name: $NAME
  sku: Standard_D2s_v3
  scaleSetPriority: Spot
  scaling:
    minSize: 0
    maxSize: 9
  spotMaxPrice: "123.456789"
  scaleDownMode: Deallocate
```

After the agent pool is created, CAPZ continuously tries to update it with this diff:
```diff
  armcontainerservice.AgentPool{
  	Properties: &armcontainerservice.ManagedClusterAgentPoolProfileProperties{
  		... // 17 identical fields
  		NodeLabels:           {"kubernetes.azure.com/scalesetpriority": &"spot"},
  		NodePublicIPPrefixID: nil,
- 		NodeTaints:           nil,
+ 		NodeTaints:           []*string{&"kubernetes.azure.com/scalesetpriority=spot:NoSchedule"},
  		OSDiskSizeGB:         nil,
  		OSDiskType:           nil,
  		... // 19 identical fields
  	},
  	ID:   nil,
  	Name: nil,
  	Type: nil,
  }
```

**What did you expect to happen:**

The AzureManagedMachinePool converges.

**Anything else you would like to add:**

**Environment:**

- cluster-api-provider-azure version: main @ b0829812e2ade8850c7023442cd17fa6dcabed51 + #3975
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
