### ISSUE TITLE
ARM64 MachinePool creation fail with "ExtensionNotFoundForCPUArchitecture"

### ISSUE THREAD

**Issue by arsiesys** [kubernetes-sigs/cluster-api-provider-azure#4016]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
- Create an AzureCluster
- Create en AzureMachinePool using a LinuxOS image with arm64 cpu architecture

We get this error at the VMSS creation request to Azure:
```
RESPONSE 404: 404 Not Found                                                                                                                                                                                                                │
│ ERROR CODE: ExtensionNotFoundForCPUArchitecture                                                                                                                                                                                            │
│ --------------------------------------------------------------------------------                                                                                                                                                           │
│ {                                                                                                                                                                                                                                          │
│   "error": {                                                                                                                                                                                                                               │
│     "code": "ExtensionNotFoundForCPUArchitecture",                                                                                                                                                                                         │
│     "message": "Extension with publisher 'Microsoft.Azure.ContainerUpstream', type 'CAPZ.Linux.Bootstrapping', and type handler version '1.0' for CPU Architecture 'arm64' was not found in the extension repository."                     │
│   }                                                                                                                                                                                                                                        │
│ }                                                                                                                                                                                                                                          │
│ --------------------------------------------------------------------------------                                                                                                                                                           │
│                                                                                               
```
I suspect that, because the VMSS doesn't exist yet, the reconcile have cpuArchitecture at nil so the test added here doesn't get used:
https://github.com/willie-yao/cluster-api-provider-azure/blob/1fcf6818c5605032a2c25569d850dc151f4c791b/azure/defaults.go#L299

**What did you expect to happen:**
The MachinePool VMSS get created in the ressource group

**Anything else you would like to add:**
The AzureMachinePool ressource definition:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachinePool
metadata:
  name: test-arm
  namespace: default
spec:
  identity: UserAssigned
  userAssignedIdentities:
  - providerID: /subscriptions/xxxx/resourcegroups/shared-identities/providers/Microsoft.ManagedIdentity/userAssignedIdentities/k8s-nodes
  location: eastus
  strategy:
    rollingUpdate:
      deletePolicy: Oldest
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    image:
      computeGallery:
        resourceGroup: "cluster-api-images"
        name: "capi-ubuntu-2204-gen2"
        subscriptionID: "xxxx"
        gallery: "testarm"
        version: "0.3.1695215304"
        plan:
          sku: 22_04-lts-arm64
          offer: demo
          publisher: demo
    networkInterfaces:
    - privateIPConfigs: 30
      subnetName: node-subnet
    osDisk:
      diskSizeGB: 30
      managedDisk:
        storageAccountType: Premium_LRS
      osType: Linux
    sshPublicKey: "xxxx"
    vmSize: Standard_D2ps_v5
```
I did some dirty changes in the image-builder to generate the arm image. The image gallery do realy see a LinuxOS and Arm64 architrcture.

**Environment:**

- cluster-api-provider-azure version: 1.11.0
- Kubernetes version: (use `kubectl version`): 1.27.3 (kind)
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04
