### ISSUE TITLE
InvalidResourceReference when trying to create an Azure Bastion with BYO network setup

### ISSUE THREAD

**Issue by MadJlzz** [kubernetes-sigs/cluster-api-provider-azure#4244]
/kind bug

**What steps did you take and what happened:**

When trying to use the bastion spec on an AzureCluster that brings it's own network infrastructure ; the capz controller is trying to deploy the resource with a reference to the resource group of the `AzureCluster` and not to the resource group of the `vnet` specified in the `networkSpec`.

Given the manifest:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: k990azc
  namespace: k990azc
spec:
  bastionSpec:
    azureBastion: {}
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: k990azc-cluster-identity
  location: uksouth
  networkSpec:
    subnets:
      - name: k990azc-control-plane-sn
        role: control-plane
      - name: k990azc-nodes-sn
        role: node
    vnet:
      name: k990azc-vnet
      resourceGroup: k990azc
  resourceGroup: k990azc-kubernetes
  subscriptionID: x.y.z
```

I would expect that the bastion host is deployed in the subnet `AzureBastionSubnet` located in vnet `k990azc-vnet` in resource group `k990azc`

Here's response code I am getting from the controller:
```
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidResourceReference
--------------------------------------------------------------------------------
{
  "error": {
    "code": "InvalidResourceReference",
    "message": "Resource /subscriptions/x.y.z/resourceGroups/K990AZC-KUBERNETES/providers/Microsoft.Network/virtualNetworks/K990AZC-VNET referenced by resource /subscriptions/x.y.z/resourceGroups/k990azc-kubernetes/providers/Microsoft.Network/bastionHosts/k990azc-azure-bastion was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
    "details": [
      {
        "code": "NotFound",
        "message": "Resource /subscriptions/x.y.z/resourceGroups/K990AZC-KUBERNETES/providers/Microsoft.Network/virtualNetworks/K990AZC-VNET not found."
      }
    ]
  }
}
--------------------------------------------------------------------------------
```

The network reference should be: `/subscriptions/x.y.z/resourceGroups/K990AZC/providers/Microsoft.Network/virtualNetworks/K990AZC-VNET` (which is the value passed in the resourceGroup property of the vnet field)

**What did you expect to happen:**

That capz controller deploys the bastion host in the virtual network defined in the `AzureCluster` spec. 

**Anything else you would like to add:**

I do believe, it all happens here:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/44a4d9a25922d2086258228c7692cc326f0eea56/azure/scope/cluster.go#L547-L565 

**Environment:**

- cluster-api-provider-azure version: Didn't find in the doc how to ouput that with `clusterctl` 😢 
- Kubernetes version: (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): kind cluster
