### ISSUE TITLE
Add artifact streaming support for managed AKS 

### ISSUE THREAD

**Issue by paulapetri** [kubernetes-sigs/cluster-api-provider-azure#4414]
/kind feature

**Describe the solution you'd like**
Add support for Artifact Streaming for AKS managed services https://learn.microsoft.com/en-us/azure/aks/artifact-streaming

**Comment by dtzar** [comment]
This theoretically should work now by [enabling the preview API ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4617) and the [CAPZ patch mechanism to enable this feature](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4527).  @paulapetri - would you like to try this out?

**Comment by dtzar** [comment]
Unfortunately, I don't see any diff in the `asoctl` yaml export after enabling this preview feature.  So without the ASO diff, the ASO patch won't do anything of course.

Here's what I ran:

```log
asoctl import azure-resource /subscriptions/###/resourcegroups/argoaks/providers/Microsoft.ContainerService/managedClusters/argoaks -o argocluster-aso.yaml 
az aks nodepool update --resource-group argoaks --cluster-name argoaks --name pool1 --enable-artifact-streaming
asoctl import azure-resource 
az aks nodepool update --resource-group argoaks --cluster-name argoaks --name pool1 --enable-artifact-streaming
/subscriptions/###/resourcegroups/argoaks/providers/Microsoft.ContainerService/managedClusters/argoaks -o argocluster-aso2.yaml 
```

Any ideas @matthchr ?

**Comment by matthchr** [comment]
artifact streaming is a property of the nodepool but you're importing the cluster.

You need to import the nodepool to see the diff.

Though, the diff will be:
```
spec:
    artifactStreamingProfile:
        enabled: true
```

I think.

**Comment by dtzar** [comment]
All I got was this:

```
---
apiVersion: containerservice.azure.com/v1api20231001
kind: ManagedClustersAgentPool
metadata:
  creationTimestamp: null
  name: pool1
spec:
  azureName: pool1
  count: 1
  enableAutoScaling: false
  enableFIPS: false
  kubeletDiskType: OS
  maxPods: 30
  mode: User
  orchestratorVersion: 1.28.5
  osDiskSizeGB: 128
  osDiskType: Managed
  osSKU: Ubuntu
  osType: Linux
  powerState:
    code: Running
  scaleDownMode: Delete
  type: Microsoft.ContainerService/managedClusters/agentPools
  upgradeSettings:
    maxSurge: 10%
  vmSize: Standard_B2s
---
```

**Comment by matthchr** [comment]
It looks like asoctl always [imports using the latest GA version we support](https://github.com/Azure/azure-service-operator/blob/d1541d241daf3dc1ee13f07b5cabc11e3721fac0/v2/cmd/asoctl/internal/importing/importable_resource.go#L73)

Which is probably a reasonable default but we might need to be able to override it.

In any case, I don't' think you specifically need `asoctl` to define the diff, it's just a convenient way to see what you need to add, right?

See [here](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20231102preview/#containerservice.azure.com/v1api20231102preview.ManagedClustersAgentPool) for the expected shape. As I said it's:
```
apiVersion: containerservice.azure.com/v1api20231102preview
kind: ManagedClustersAgentPool
spec:
    artifactStreamingProfile:
        enabled: true
```
