### ISSUE TITLE
Add support for out-of-tree cloud provider components

### ISSUE THREAD

**Issue by ritazh** [kubernetes-sigs/cluster-api-provider-azure#456]
/kind feature

**Describe the solution you'd like**
Add support to use  [out-of-tree cloud provider components](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-controller-manager.md)

**Anything else you would like to add:**
PR for reference: https://github.com/Azure/aks-engine/pull/2161

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
@ritazh I think this might already be possible by tweaking the [kubeadm config](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/templates/cluster-template.yaml#L40-L73) to follow [these](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-controller-manager.md#usage). ie, it should look something like this:

```
    kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cloud-provider: external
          azure-container-registry-config: /etc/kubernetes/azure.json
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data["local_hostname"] }}'
        kubeletExtraArgs:
          cloud-provider: external
          azure-container-registry-config: /etc/kubernetes/azure.json
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 20m
      controllerManager:
        extraArgs:
          cloud-provider: external
```

Still figuring out the azure ccm part... 

/assign
