### ISSUE TITLE
Add option to enable monitoring on cluster

### ISSUE THREAD

**Issue by grzesuav** [kubernetes-sigs/cluster-api-provider-azure#4571]
/kind feature

**Describe the solution you'd like**
I would like to set `az aks update --enable-azure-monitor-metrics` via ClusterAPI

**Anything else you would like to add:**
In terraform it is done by https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#monitor_metrics

**Environment:**

- cluster-api-provider-azure version:  N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by dtzar** [comment]
I believe this could be enabled by using the recently merged marketplace PR #3513 
There is an extension called `microsoft.azuremonitor.containers.metrics`
Since this functionality hasn't been released yet, no easy way to test it unfortunately.

**Comment by grzesuav** [comment]
It seems it can be done by using azure service operator https://azure.github.io/azure-service-operator/reference/containerservice/v1api20231001/#containerservice.azure.com/v1api20231001.ManagedClusterAzureMonitorProfile

**Comment by willie-yao** [comment]
#4678 Has been resolved. Let me know if the extension does the trick.

**Comment by dtzar** [comment]
I verified this does install the metrics pods using this configuration.

```
  extensions:
  - name: monitoring
    extensionType: "microsoft.azuremonitor.containers.metrics"
    plan:
      name: "microsoft.azuremonitor.containers.metrics"
      publisher: "Azure Monitor Metrics"
```

I did notice though in your terraform docs link this: 

```
If deploying Managed Prometheus, the monitor_metrics properties are required to configure the cluster for metrics collection. If no value is needed, set properties to null.
```

It doesn't really say where that is configured.  Do you know more there @grzesuav?
