### ISSUE TITLE
CAPZ 1.13.1 fails to use existing virtualNetwork from a different rg

### ISSUE THREAD

**Issue by ionutleca** [kubernetes-sigs/cluster-api-provider-azure#4595]
/kind bug

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
Created a resource like:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: example-cp
  namespace: example-ns
spec:
  resourceGroupName: example-cp-rg
  .
  .
  .
  virtualNetwork:
    cidrBlock: ***
    name: example-vnet
    resourceGroup: example-vnet-rg
```
Where I'm trying to reference an existing VNET from a resource group different than the one of the _AzureManagedControlPlane_.

CAPZ [will set](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/da0b52d988f317b758a95bdc560267c9874ab622/azure/services/virtualnetworks/spec.go#L70) the _VirtualNetwork.Spec.Owner_ to _example-vnet-rg_

ASO will go through [this code](https://github.com/Azure/azure-service-operator/blob/d1c7f88d3c4eac7ed2cdac9b57c70b4861273eb5/v2/internal/reconcilers/common.go#L127) during it's reconciliation loop and fail to find _ResourceGroup: example-vnet-rg_ inside the cluster

The _AzureManagedControlPlane_ will be stuck at:
```
virtualnetworks failed to create or update. err: resource is not Ready:                                                                   │
  Owner "example-vnet-rg, Group/Kind: resources.azure.com/ResourceGroup" cannot be                                                                     │
  found. Progress is blocked until the owner is created.. Object will be requeued                                                                   │
  after 20s  
```

_
**What did you expect to happen:**
CAPZ to be able to reference the existing vnet from that resource group.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 1.13.1
- Kubernetes version: (use `kubectl version`): 1.27.9
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04
