### ISSUE TITLE
clusterclass control-plane namingStrategy is not applied

### ISSUE THREAD

**Issue by arno-pons** [kubernetes-sigs/cluster-api-provider-azure#4597]
/kind bug

**What steps did you take and what happened:**

Deploying an Azure cluster using a clusterclass with a [spec.controlPlane.namingStrategy.template](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass#defining-a-custom-naming-strategy-for-controlplane-objects) attribute with value:
`"{{ .cluster.name }}-control-plane-{{ .random }}"`

doesn't create capz objects name (azuremachinetemplate, azuremachine and azure VM) matching this strategy.
Only capi objects (kubeadmcontrolplane and machine) are correctly named.
capz objects seems to be named with default strategy:
`"{{ .cluster.name }}-{{ .random }}"`

Here the clusterclass configuration:

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: my-cc
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: my-kcpt
      namespace: default
    namingStrategy:
      template: "{{ .cluster.name }}-control-plane-{{ .random }}"
[...]
```

**What did you expect to happen:**

Names of control-plane VM and nodes should match clusterclass namingStrategy.

**Anything else you would like to add:**

clusterclass with same namingStrategy for another infrastructure provider (vSphere capv) results in VM and node names matching the naming strategy.

**Environment:**

- capi version: 1.6.1 
- capz version: 1.13.0
- kubernetes version: v1.28.5

**Comment by willie-yao** [comment]
Hi @arno-pons! Adding the `namingStrategy` field to the controlPlane spec only applies the strategy to the controlplane resources such as kubeadmcontrolplane. You can specify `namingStrategy` for your `machineDeployments` or `machinePools` workers and the names of the Azure resources should match the `namingStrategy`.

I just verified this by adding `namingStrategy` like so:
```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: my-cc
  namespace: default
spec:
  workers:
    machineDeployments:
    - class: ${CLUSTER_NAME}-worker
      namingStrategy:
        template: "{{ .cluster.name }}-foo-{{ .random }}"
```

`kubectl get azuremachine` shows the following: 
```
NAME                                             READY   SEVERITY   REASON                    STATE   AGE
willie-clusterclass-9406-foo-44xp6-8rn9x         False   Info       Creating                          70s
willie-clusterclass-9406-foo-rb6ps-rpr7f-pj6zt   False   Info       WaitingForBootstrapData           4m33s
willie-clusterclass-9406-foo-rb6ps-rpr7f-xrjnn   False   Info       WaitingForBootstrapData           4m33s
```
