### ISSUE TITLE
Cluster fails to reconcile with `etcdserver: request is too large`

### ISSUE THREAD

**Issue by danilo404** [kubernetes-sigs/cluster-api-provider-azure#4649]
/kind bug

**What steps did you take and what happened:**
A cluster was created with the following `AzureManagedControlPlane` network configuration
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
spec:
  networkPlugin: azure
  networkPolicy: azure
  virtualNetwork:
    cidrBlock: 10.0.0.0/16
    name: examplecluster
    resourceGroup: examplecluster-rg
    subnet:
      cidrBlock: 10.0.0.0/16
```

The cluster has many `AzureManagedMachinePool` objects, each with `maxPods` between 80 and 150.

Reconciliation for the cluster worked fine for a long time, until started failing with:
```
E0315 17:13:54.206966       1 controller.go:329] "msg"="Reconciler error" "error"="updating mynamespace/examplecluster-vnet-examplecluster-subnet resource status: etcdserver: request is too large" "logger"="controllers" "name"="examplecluster-vnet-examplecluster-subnet" "namespace"="examplenamespace" "reconcileID"="..."
```

**What did you expect to happen:**
The cluster to continue to be reconciled successfully

**Anything else you would like to add:**

While investigating the issue we noticed the `virtualnetworkssubnets.network.azure.com` CR is populated with thousands of entries for the `ipConfigurations` field, it seems like the entries are IP reservations for Pods, the number matches the number of Pods per node, repeated for every VM in the VMSS for example:
```
apiVersion: network.azure.com/v1api20201101
kind: VirtualNetworksSubnet
...
status:
  conditions:
  ipConfigurations:
  - id: /subscriptions/<subscription>/resourceGroups/<resource group>/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/.../ipConfigurations/IPCONFIG1
  - id: /subscriptions/<subscription>/resourceGroups/<resource group>/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/.../ipConfigurations/IPCONFIG2
```

Checking the approximate size of the payload this object would have at run time confirms it's above the AKS etcd request size limit of 2mb:
```
az network vnet subnet show --ids <my subnet resource id> > subnet.json
ls -hl subnet.json
-rw-r--r--  1 danilo  staff   2.9M Mar 14 17:21 subnet.json
```

We suspect the issue is caused by the large number of `ipConfigurations` that come from Azure and are added to this field, which result from the combination of the large number nodes multiplied by the number of `maxPods` per node. When the cluster scales up above a certain number, this object can no longer be persisted due its size.

**Environment:**

- cluster-api-provider-azure version: v1.13.0
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by mboersma** [comment]
@danilo404 I'm trying to reproduce this so I can investigate, but haven't so far.

I started with CAPZ v1.13.0 and created an AKS cluster with similar network config to what you posted, and 10 node pools with 1000 nginx pods. But I'm not seeing any `ipConfigurations` on the `VirtualNetworksSubnet`:

```yaml
% kubectl get VirtualNetworksSubnet -o yaml                              
apiVersion: v1
items:
- apiVersion: network.azure.com/v1api20201101
  kind: VirtualNetworksSubnet
  spec:
    addressPrefix: 10.0.0.0/16
    addressPrefixes:
    - 10.0.0.0/16
    azureName: aks-etcd-1234
    owner:
      name: aks-etcd-1234-vnet
  status:
    addressPrefix: 10.0.0.0/16
    conditions:
    id: /subscriptions/00000000-0000-0000-0000-00000000000/resourceGroups/aks-etcd-1234/providers/Microsoft.Network/virtualNetworks/aks-etcd-1234-vnet/subnets/aks-etcd-1234
    name: aks-etcd-1234
    privateEndpointNetworkPolicies: Disabled
    privateLinkServiceNetworkPolicies: Enabled
    provisioningState: Succeeded
    type: Microsoft.Network/virtualNetworks/subnets
kind: List
```

Sorry, I must be missing something. Any ideas on what other configuration might be relevant? I assume I wouldn't need to scale up as far as you have just to see the way `ipConfigurations` is being used.
