### ISSUE TITLE
Documentation on how to configure  CAPZ clusters to pull from a Private ACR registry

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes-sigs/cluster-api-provider-azure#4679]
/kind doc

[Before submitting an issue, have you checked the [Troubleshooting Guide](https://capz.sigs.k8s.io/topics/troubleshooting.html)?]

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Add documentation on how to configure kubelet in CAPZ to pull from a Private ACR registry. It is alluded to here https://capz.sigs.k8s.io/topics/vm-identity.html?highlight=acrpull#how-to-use-managed-identity but there aren't detailed docs on the exact set up

**What did you expect to happen:**
Make it easy to configure CAPZ clusters to use private ACR registry for management and workload clusters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by jsturtevant** [comment]
This will be part of it https://cloud-provider-azure.sigs.k8s.io/topics/credential-provider/

**Comment by jsturtevant** [comment]
The credential provider is already dropped on the capz nodes:

```
 cat /var/lib/kubelet/credential-provider-config.yaml
kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1
providers:
- name: acr-credential-provider
  apiVersion: credentialprovider.kubelet.k8s.io/v1
  defaultCacheDuration: 10m
  matchImages:
  - "*.azurecr.io"
  - "*.azurecr.cn"
  - "*.azurecr.de"
  - "*.azurecr.us"
  args:
  - /etc/kubernetes/azure.json
 ```
