### ISSUE TITLE
AMCP needs explicit IP CIDR block when referencing existing VNETS

### ISSUE THREAD

**Issue by ionutleca** [kubernetes-sigs/cluster-api-provider-azure#4970]
/kind bug

**What steps did you take and what happened:**
Tried to deploy an AzureManagedControlPlane resource without mentioning the vnet and subnet IP CIDR blocks:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: example-cp
  namespace: example-ns
spec:
  resourceGroupName: example-cp-rg
  .
  .
  .
  virtualNetwork:
    cidrBlock: ""
    name: example-vnet
    resourceGroup: example-vnet-rg
    subnet:
            cidrBlock: ""
            name: example-subnet
            serviceEndpoints: []
```
 got
 
 ```
 	RESPONSE 400: 400 Bad Request
	ERROR CODE: AddressPrefixStringCannotBeNullOrEmpty
	--------------------------------------------------------------------------------
	{
	  "error": {
	    "code": "AddressPrefixStringCannotBeNullOrEmpty",
	    "message": "Address prefix string for resource /subscriptions/b65b0225-ce9b-4a79-9dd9-c00071d40d64/resourceGroups/dvts-ondmd-dan-we-02-g-rg/providers/Microsoft.Network/virtualNetworks/dvts-ondmd-dan-we-02-g-test-vnet cannot be null or empty.",
	    "details": []
	  }
	}
	--------------------------------------------------------------------------------
	. Object will not be requeued
```

**What did you expect to happen:**
Looking at how CAPZ [defaults](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/api/v1beta1/azuremanagedcontrolplane_default.go#L73) those values and how they [are ignored](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/managedcontrolplane.go#L378) for managed control planes, we thought there is no need for us to maintain those values.

Since we reference existing vnets (managed by another team/system), not needing to maintain details about the existing resources and just reference them by rg+name would be ideal.

**Anything else you would like to add:**
If this is fixed in newer versions, I'd like to know if using empty string for this case is indeed the right choice or the recommendation is to keep the real IP CIDRS there and not use any mock values.

**Environment:**

cluster-api-provider-azure version: 1.13.1
Kubernetes version: (use kubectl version): 1.27.9
OS (e.g. from /etc/os-release): Ubuntu 20.04
