### ISSUE TITLE
Clarify `identityRef` and `identity` fields in `AzureManagedControlPlaneClassSpec `

### ISSUE THREAD

**Issue by djryanj** [kubernetes-sigs/cluster-api-provider-azure#5202]
When deploying a managed control plane thus:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: poc
spec:
  location: canadacentral
  resourceGroupName: rg
  # sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
  subscriptionID: 00000000-0000-0000-0000-000000000000 # fake uuid
  version: v1.30.0
  networkPolicy: azure
  networkPlugin: azure
  nodeResourceGroupName: rg2
  sku:
    tier: Free # or Standard
  identity:
    type: UserAssigned
    userAssignedIdentityResourceID: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uai
  identityRef:
    kind: AzureClusterIdentity
    name: cluster-identity
    namespace: to-be-patched
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: cluster-identity
spec:
  type: WorkloadIdentity
  allowedNamespaces:
    list:
    - <cluster-namespace>
  tenantID: <your-tenant-id>
  clientID: <your-client-id>

```

If you don't provide `identity` for a user assigned identity, it won't deploy with the user UAI, even though `identityRef` is provided (and the intention is to use that reference). In my case, both `identity` and `identityRef` point to the same identity. I realize that may not be the intention, but I can't find any descriptive documentation on what each really does to be able to understand each one.

From https://capz.sigs.k8s.io/reference/v1beta1-api#infrastructure.cluster.x-k8s.io/v1beta1.AzureManagedControlPlaneClassSpec:

> <html><body>

identityRef <br> Kubernetes core/v1.ObjectReference | IdentityRef is a reference to a AzureClusterIdentity to be used when reconciling this cluster
-- | --

</body>
</html>

And:

> <html><body>

identity  <br> Identity | (Optional) Identity configuration used by the AKS control plane.
-- | --

</body>
</html>

Given the names, I would _assume_ that they do the same thing, where one is a reference and the other is a directly encoded value.  However, based on the CRD documentation, it seems like one is used by CAPI to reconcile, and the other is used by the cluster itself.

Any clarity would be appreciated.
