### ISSUE TITLE
Cannot create FleetsMembers resources when using AzureASOManagedControlPlane

### ISSUE THREAD

**Issue by markjgardner** [kubernetes-sigs/cluster-api-provider-azure#5333]
/kind bug

**What steps did you take and what happened:**
When attempting to create a cluster using ```AzureASOManagedControlPlane``` and register it with fleet using ```fleetsmembers.containerservice.azure.com``` resourcetype, reconciliation fails because the FleetsMembers resource requires an owner reference of type ```fleet.containerservice.azure.com```. This CRD, however, is not registered as part of the CAPZ install on the management cluster.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOManagedControlPlane
metadata:
  name: fleet-cluster1-aks
spec:
  resources:
    - apiVersion: containerservice.azure.com/v1api20210501
      kind: ManagedCluster
      metadata:
        name: fleet-cluster1-aks
      spec:
        location: westus3
        owner:
          name: myfleet-rg
        dnsPrefix: fleet-cluster1
        identity:
          type: SystemAssigned
    - apiversion: containerservice.azure.com/v1api20230315preview
      kind: Fleet
      metadata:
        name: hub-fleet
        annotations:
          serviceoperator.azure.com/reconcile-policy: "skip"
      spec:
        owner:
          name: hub-rg
    - apiVersion: containerservice.azure.com/v1api20230315preview
      kind: FleetsMember
      metadata:
        name: fleet-cluster1-aks
      spec:
        group: apps
        owner:
          name: hub-fleet
        clusterResourceReference:
          group: containerservice.azure.com
          kind: ManagedCluster
          name: fleet-cluster1-aks
```
`failed to get owner: couldn't resolve reference hub-fleet, Group/Kind: containerservice.azure.com/Fleet: no matches for kind "Fleet" in version "containerservice.azure.com/v1api20230315previewstorage"`

```console
$> kubectl api-resources --api-group containerservice.azure.com
NAME                        SHORTNAMES   APIVERSION                                        NAMESPACED   KIND
fleetsmembers                            containerservice.azure.com/v1api20230315preview   true         FleetsMember
managedclusters                          containerservice.azure.com/v1api20210501          true         ManagedCluster
managedclustersagentpools                containerservice.azure.com/v1api20210501          true         ManagedClustersAgentPool
```

**What did you expect to happen:**
Reconciliation should have detected the existing hub and registered the cluster as a member.

**Anything else you would like to add:**
[ASO Fleet resource docs](https://azure.github.io/azure-service-operator/reference/containerservice/v1api20230315preview/#containerservice.azure.com/v1api20230315preview.Fleet)

**Environment:**

- cluster-api-provider-azure version: v1.17.2
- Kubernetes version: v1.30.6
- OS (e.g. from `/etc/os-release`): AKSUbuntu-2204gen2containerd-202411.12.0

**Comment by markjgardner** [comment]
As a workaround, you must use the `armId` parameter for the owner reference.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOManagedControlPlane
metadata:
  name: fleet-cluster1-aks
spec:
  resources:
    - apiVersion: containerservice.azure.com/v1api20210501
      kind: ManagedCluster
      metadata:
        name: fleet-cluster1-aks
      spec:
        location: westus3
        owner:
          name: myfleet-rg
        dnsPrefix: fleet-cluster1
        identity:
          type: SystemAssigned
    - apiVersion: containerservice.azure.com/v1api20230315preview
      kind: FleetsMember
      metadata:
        name: fleet-cluster1-aks
      spec:
        group: apps
        owner:
          arm-id: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/hub-rg/providers/Microsoft.ContainerService/fleets/hub-fleet
        clusterResourceReference:
          group: containerservice.azure.com
          kind: ManagedCluster
          name: fleet-cluster1-aks
```
