### ISSUE TITLE
Question: When will be the beta release for AzureASOManagedCluster



### ISSUE THREAD

**Issue by RSE132** [kubernetes-sigs/cluster-api-provider-azure#5642]
AzureASOManagedCluster

Currently I see that it is still in alpha release so just wondering when the beta release will be available for asomanagedclusters

```
spec:
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: AzureASOManagedClusterTemplate
```

Ref:- [October 17, 2024 meeting notes](https://docs.google.com/document/d/1P2FrRjuCZjGy0Yh72lwWCwmXekSEkqliUVTmJy_ETIk/edit?tab=t.0)
