### ISSUE TITLE
Applied ASO resource through AzureASOManagedControlPlaneTemplate changes the API version after apply

### ISSUE THREAD

**Issue by RSE132** [kubernetes-sigs/cluster-api-provider-azure#5649]
/kind bug

[Before submitting an issue, have you checked the Troubleshooting Guide [self-managed](https://capz.sigs.k8s.io/self-managed/troubleshooting.html) & [managed](https://capz.sigs.k8s.io/managed/troubleshooting.html)?]

**What steps did you take and what happened:**
When I apply an AzureASOManagedControlPlaneTemplate with the resource apiVersion set to `containerservice.azure.com/v1api20231001`, the resulting ManagedCluster that gets created has a different `apiVersion: containerservice.azure.com/v1api20210501`.

**applied AzureASOManagedControlPlaneTemplate**
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOManagedControlPlaneTemplate
metadata:
  name: first-temporal-build-cluster
  namespace: first-temporal-build-cluster
spec:
  template:
    spec:
      resources:
      - apiVersion: containerservice.azure.com/v1api20231001
        kind: ManagedCluster
        metadata:
          annotations:
            serviceoperator.azure.com/credential-from: first-temporal-build-cluster-aso-credential
            serviceoperator.azure.com/reconcile-policy: manage
          name: first-temporal-build-cluster
          namespace: first-temporal-build-cluster
```

**resulting ManagedCluster**
```
apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedCluster
metadata:
  annotations:
    serviceoperator.azure.com/credential-from: first-temporal-build-cluster-aso-credential
    serviceoperator.azure.com/latest-reconciled-generation: "5"
    serviceoperator.azure.com/operator-namespace: capz-system
```
**What did you expect to happen:**
I would expect to see that the resulting ManagedCluster also uses apiVersion: containerservice.azure.com/v1api20231001.

**Anything else you would like to add:**
Current Api Version that comes along with the CRD installation by capz

|VERSION|	STORAGE|	SERVED|
|---|---|---|
|v1api20210501|	false|	true|
|v1api20210501storage|	false|	true|
|v1api20230201|	false|	true|
|v1api20230201storage|	false|	true|
|v1api20231001|	false|	true|
|v1api20231001storage|	false|	true|
|v1api20231102preview|	false|	true|
|v1api20231102previewstorage|	false|	true|
|v1api20240402preview|	false|	true|
|v1api20240402previewstorage|	false|	true|
|v1api20240901|	false|	true|
|v1api20240901storage|	true|	true|

**Environment:**
```
NAME                    NAMESPACE                           TYPE                     CURRENT VERSION
bootstrap-kubeadm       capi-kubeadm-bootstrap-system       BootstrapProvider        v1.9.7
control-plane-kubeadm   capi-kubeadm-control-plane-system   ControlPlaneProvider     v1.9.7
cluster-api             capi-system                         CoreProvider             v1.9.7
infrastructure-azure    capz-system                         InfrastructureProvider   v1.19.4
```
- Kubernetes version: (use `kubectl version`): 1.30.7

**Comment by penoux** [comment]
We have the same behaviour using AzureASOManagedControlPlane manifest. having `containerservice.azure.com/v1api20240202preview` (supported in CRDs list): the resulting ManagedCluster that gets created has a different apiVersion: `containerservice.azure.com/v1api20210501`.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: AzureASOManagedControlPlane
metadata:
  name: test-cluster
  namespace: test
spec:
  resources:
  - apiVersion: containerservice.azure.com/v1api20240402preview
    kind: ManagedCluster
    metadata:
      name: test-cluster
```

Result:

```yaml
apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedCluster
metadata:
  name: test-cluster
  namespace: sylva-system
```

What is a bit weird is that the effective options of newer apiVersions than v1api20210501 seem supported (even preview)...
