### ISSUE TITLE
Improve local debugging experience

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-azure#588]
/kind feature

**Describe the solution you'd like**
It would be great if there was an easier way to debug locally, especially with the the webhooks still being used. 

There is a discussion on #572 around this with some ideas.

**Anything else you would like to add:**
My current debugging workflow is:
1. make create-cluster
2.  Delete the deployment and webhook configuration:
```bash
kubectl delete deployment capz-controller-manager -n capz-system
kubectl delete ValidatingWebhookConfiguration capz-validating-webhook-configuration
```
3.  Set breakpoints in the capz code somewhere
4. Use a VSCode debug launch configuration to launch the manager
5. Apply cluster yaml

This approach is ok if you are ok ignoring the webhooks.

**Environment:**

/cc: @devigned

**Comment by richardcase** [comment]
I wondered if something like this might work:

1. For debugging change the entrypoint from /manager to using delve with remote debugging enabled [ "dlv", "debug", "/manager", "--listen=:35000", "--headless=true", "--api-version=2", "--log" ]
2. Patch the manager deployment to expose the debugger port
3. Start kind exposing the debugging port using something like the following:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 35000
    hostPort: 35000
    protocol: TCP
```
4. Create a VSCode launch configuration that instructs delve to debug remotely using the port used above
