### ISSUE TITLE
Validating webhooks seem to not be working

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/cluster-api-provider-azure#608]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

After #556 merged, I tried creating a cluster with an invalid vnet resource group name and got no webhook error, but the Azure SDK showed errors in the logs. Setting the replicas to 0 for KCP does return an error, so CAPI webhooks seem to be working as expected.

**What did you expect to happen:**

Creating an invalid resource should result in a creation failure with a validation error.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- cluster-api-provider-azure version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by CecileRobertMichon** [comment]
What @devigned @alexeldeib and I have observed so far:

- This repros 100% of the time
- Applies to all CAPZ webhooks
- CAPI webhooks work
- webhooks are created on the cluster:
```
kubectl get ValidatingWebhookConfiguration
NAME                                                          WEBHOOKS   AGE
capi-kubeadm-control-plane-validating-webhook-configuration   1          74m
capi-validating-webhook-configuration                         6          74m
capz-validating-webhook-configuration                         3          74m
cert-manager-webhook                                          1          77m
``` 

- capi-webhook-system capz-manager logs show:
```
[manager] I0514 19:09:17.933157       7 webhook.go:123] controller-runtime/builder "msg"="Registering a validating webhook"  "GVK"={"Group":"infrastructure.cluster.x-k8s.io","Version":"v1alpha3","Kind":"AzureMachine"} "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachine"
[manager] I0514 19:09:17.933273       7 server.go:121] controller-runtime/webhook "msg"="registering webhook"  "path"="/validate-infrastructure-cluster-x-k8s-io-v1alpha3-azuremachine"
```
and
```
[kube-rbac-proxy] I0514 19:09:27.018994       1 main.go:243] Starting TCP socket on 0.0.0.0:8443
[kube-rbac-proxy] I0514 19:09:27.020565       1 main.go:250] Listening securely on 0.0.0.0:8443
```

- AzureClusterWebhook looks like:
```
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: REDACTED
    service:
      name: capz-webhook-service
      namespace: capi-webhook-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-azurecluster
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.azurecluster.infrastructure.cluster.x-k8s.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - azurecluster
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```

**Comment by CecileRobertMichon** [comment]
After further inspection, it seems that only the fields validated by upstream k8s throw errors for CAPI resources so it looks like CAPI webhooks are also affected.
For example, (provided by @alexeldeib):

https://github.com/kubernetes-sigs/cluster-api/blob/15300a4b6924dcca85c94efdfc06fb80dccaf47a/api/v1alpha3/cluster_webhook.go#L78

```
  spec:
    clusterName: capz-cluster
    minReadySeconds: 0
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 1
    selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: capz-cluster
        cluster.x-k8s.io/deployment-name: capz-cluster-md-0
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          cluster.x-k8s.io/cluster-name: capz-cluster
          cluster.x-k8s.io/deployment-name: capz-cluster-md-0
      spec:
        bootstrap:
          configRef:
            apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
            kind: KubeadmConfigTemplate
            name: capz-cluster-md-0
        clusterName: capz-cluster
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
          kind: AzureMachineTemplate
          name: capz-cluster-md-0
          namespace: system
        version: v1.17.4
  status:
    observedGeneration: 2
    phase: ScalingUp
    replicas: 3
    selector: cluster.x-k8s.io/cluster-name=capz-cluster,cluster.x-k8s.io/deployment-name=capz-cluster-md-0
    unavailableReplicas: 3
    updatedReplicas: 1
```

The above spec should not be valid since it has namespace default for cluster and system for the infra ref.

cc @detiber @vincepri @ncdc
